### PR TITLE
fix: print an info message when NODE_ENV is set to production

### LINKED ISSUE #4309: pnpm fails to install nexus-prisma in production on Vercel
### pnpm version:
6.30.0

### Code to reproduce the issue:
Use ``nexus-prisma`` and NextJS on Vercel with ``pnpm``

### Expected behavior:
The dependencies successfully resolve

### Actual behavior:
See in https://github.com/prisma/nexus-prisma/issues/189

### Additional information:
This issue **does not happen in local environment**, in my development environment it worked fine without any issues.

I initially thought this is a Prisma/nexus-prisma issue but [this comment](https://github.com/prisma/nexus-prisma/issues/189#issuecomment-1033016117) addressed it's ``pnpm``'s issue as ``yarn`` (and ``npm``) are not having such behavior

 - `node -v` prints: Vercel's NodeJS version
 - Windows, macOS, or Linux?: Linux (on Vercel)

### PR DESCRIPTION
**Pull request by zkochan**
close #4309

### CODE REVIEW

**Review by BlackHole1 — APPROVED** [review]

**Comment by zkochan** [comment]
@BlackHole1 thank you for being so active in the repository lately.

File: packages/default-reporter/src/reporterForClient/reportSummary.ts [hunk 1]
```diff
@@ -35,6 +35,7 @@ export default (
   },
   opts: {
     cwd: string
+    env: Record<string, string | undefined>
```
Comment (BlackHole1) [inline packages/default-reporter/src/reporterForClient/reportSummary.ts]: nit: `NodeJS.ProcessEnv`
