### PR TITLE
fix(sbom): resolve licenses for git-sourced dependencies

### LINKED ISSUE #11260: pnpm sbom: reports `NOASSERTION` for git direct dependencies
### Verify latest release
- [x] I verified that the issue exists in the latest pnpm release

### pnpm version
11.0.0-rc.0

### Which area(s) of pnpm are affected?
CLI

### Link to the code that reproduces this issue
Minimal repro below (single `package.json`, one public git dependency).

### Reproduction steps

1. Create a directory with this `package.json`:

   ```json
   {
     "name": "sbom-git-repro",
     "version": "1.0.0",
     "private": true,
     "dependencies": {
       "left-pad": "git+https://github.com/stevemao/left-pad.git"
     }
   }
   ```

2. Install and generate the SBOM:

   ```sh
   pnpm install
   pnpm sbom --sbom-format spdx
   ```

3. Inspect the `left-pad` entry.

For comparison, run the same steps with npm:

   ```sh
   rm -rf node_modules pnpm-lock.yaml
   npm install
   npm sbom --sbom-format spdx
   ```

### Describe the Bug

`pnpm sbom` emits `licenseDeclared: "NOASSERTION"` for direct dependencies installed from git URLs (`git+https://`, `git+ssh://`, `github:` shorthand), even when the fetched package's `package.json` declares a valid `license`. The same dependency is resolved correctly by `npm sbom`.

Output from `pnpm sbom --sbom-format spdx` for the repro above:

```json
{
  "name": "left-pad",
  "versionInfo": "1.3.0",
  "licenseConcluded": "NOASSERTION",
  "licenseDeclared": "NOASSERTION",
  "copyrightText": "NOASSERTION"
}
```

Output from `npm sbom --sbom-format spdx` for the same project:

```json
{
  "name": "left-pad",
  "versionInfo": "1.3.0",
  "licenseDeclared": "MIT"
}
```

`left-pad@1.3.0` declares `"license": "MIT"` in its manifest. The package manifest is present after install, so license resolution appears to be skipped specifically for non-registry (git) sources.

### Expected Behavior

`pnpm sbom` should resolve the license of git-sourced dependencies from the fetched package's `package.json` (and fall back to `LICENSE` files), matching the behavior of `npm sbom` and of `pnpm sbom` for registry-sourced packages. For the repro above, the expected output is `"licenseDeclared": "MIT"`.

### Which Node.js version are you using?
25.9.0

### Which operating systems have you used?
- [x] macOS

### If your OS is Linux based
N/A

### PR DESCRIPTION
**Pull request by Saturate**
## Summary

- `readPackageFileMap` didn't handle `type: 'git'` resolutions, so `pnpm sbom` reported `NOASSERTION` and `pnpm licenses` threw errors for any dependency installed from a git URL (`git+https://`, `git+ssh://`, `github:` shorthand)
- Added a two-line branch for `packageResolution.type === 'git'` that looks up the store index via `gitHostedStoreIndexKey`, matching how the installer stores these packages
- Both `pnpm sbom` and `pnpm licenses` go through the same `readPackageFileMap` code path, so both are fixed

## Test plan / verify

- [x] New `readPackageFileMap` unit tests covering all resolution types: registry (integrity), git-hosted tarball, `type: 'git'`, missing git dep (ENOENT), unknown type
- [x] End-to-end `getPkgInfo` tests that write real `package.json` files to the CAFS layout and verify license extraction works for both registry and git dependencies
- [x] All existing `license-scanner` tests still pass

Closes #11260

### CODE REVIEW

**Comment by aarond-sp** [comment]
## Repro: `pnpm sbom` still emits NOASSERTION for git dependencies

This PR fixes `pnpm licenses` for git-sourced deps, but `pnpm sbom` still emits `NOASSERTION`.

### Setup

`package.json`:
```json
{
  "name": "sbom-git-repro",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "left-pad": "github:stevemao/left-pad#2fca6157fcca165438e0f9495cf0e5a4e6f71349"
  }
}
```

`pnpm-workspace.yaml`:
```yaml
allowBuilds:
  left-pad: true
```

### Steps

```bash
pnpm install
pnpm licenses list
pnpm sbom --sbom-format spdx | grep -E '"name"|license'
```

### Expected vs actual

`pnpm licenses list` — correct (fix works here):
```
┌──────────┬─────────┐
│ Package  │ License │
├──────────┼─────────┤
│ left-pad │ MIT     │
└──────────┴─────────┘
```

`pnpm sbom --sbom-format spdx` — still broken:
```json
"name": "left-pad",
"licenseConcluded": "NOASSERTION",
"licenseDeclared":  "NOASSERTION"
```

The `package.json` in the store has `"license": "MIT"`, so the SBOM should report MIT.

**Comment by Saturate** [comment]
Looking into it!

Edit:

A bad test from my side :) fixed both test and implementation.

**Comment by aarond-sp** [comment]
> Looking into it!
> 
> Edit:
> 
> A bad test from my side :) fixed both test and implementation.

Looking good, we don't have any NOASSERTION's anymore for our project. Thank you :)

```
❯  grep '"licenseDeclared": "NOASSERTION"' pnpm.spdx.old | wc -l
       9
❯  grep '"licenseDeclared": "NOASSERTION"' pnpm.spdx | wc -l
       0
```

File: store/pkg-finder/src/index.ts [hunk 1]
```diff
@@ -53,6 +53,8 @@ export async function readPackageFileMap (
       packageResolution.integrity as string,
       parsedId.nonSemverVersion ?? `${parsedId.name}@${parsedId.version}`
     )
+  } else if (packageResolution.type === 'git') {
+    pkgIndexFilePath = gitHostedStoreIndexKey(packageId, { built: true })
```
Comment (zkochan) [inline store/pkg-finder/src/index.ts]: well, this is a less frequent type of dependency, so it should be after the tarball check.

**Review by zkochan — APPROVED** [review]

File: store/pkg-finder/src/index.ts (hunk 1 above)
Comment (Saturate) [reply store/pkg-finder/src/index.ts]: Makes sense, thanks I've fixed it.
