### PR TITLE
fix: issue with passing properly args to the comannd

### LINKED ISSUE #1124: `pnpm run` is not compatible with `npm run`
### Expected behavior:

pnpm needs to properly pass the --flag=true to the command that is specfied in the "build" script. Just like npm would do that.

### Actual behavior:

Instead, it looks like that the delimiter `--` is used to stop args parser of pnpm from parsing the rest of the arguments, and the rest of the arguments are passed as flag for the `npm run` command.

### Additional information:

I was able to fix the issue by running as `pnpm run build -- -- --flag=true`, passing `--` twice, one to stop parser of pnpm from continuing parsing arguments and second to stop parser of npm from parsing flags.

This behaviour might be good for the case where users would want to pass flags to `npm run`. But this is not intuitive and the only flag that `npm run` accepts is `--silent`, so maybe there is a different way to handle this flag (unless it is already handled correctly)

- `node -v === 'v9.11.1'`
- `npm -v === '5.8.0'`
- Linux

### PR DESCRIPTION
**Pull request by devocija-it**
pnpm does not properly pass arguments to command that is specified in the build script as npm does, with this change pnpm behaves exactly like npm.

Closes #1124

### CODE REVIEW

File: packages/pnpm/src/main.ts [hunk 1]
```diff
@@ -205,6 +205,16 @@ export default async function run (argv: string[]) {
     setTimeout(() => {
       // `pnpm install ""` is going to be just `pnpm install`
       const cliArgs = cliConf.argv.remain.slice(1).filter(Boolean)
+
+      // checking for args that should be passed to the command that is specfied in the build script.
+      const argIndex = cliArgs.findIndex((value) => {
```
Comment (zkochan) [inline packages/pnpm/src/main.ts]: This is how argIndex should be found: 

```ts
const argIndex = cliConf.argv.cooked.indexOf('--') - 1
```

Also, I would give the variable some more meaningful name. `dashDashIndex` or `doubleDashIndex` or `paramsSeparatorIndex`

File: packages/pnpm/test/run.ts [hunk 2]
```diff
@@ -18,3 +18,16 @@ test('pnpm run: returns correct exit code', async (t: tape.Test) => {
...
+test('pass the args to the command that is specfied in the build script', async t => {
+  const project = prepare(t, {
+    scripts: {
+      test: 'ts-node test'
+    },
+  })
+
+  const result = execPnpmSync('run', 'test', '--', '--flag=true')
+
+  t.ok((result.stdout as Buffer).toString('utf8').match(/ts-node test "--flag=true"/), 'command was successfull')
```
Comment (zkochan) [inline packages/pnpm/test/run.ts]: Typo. It should be "successful" with a single "l" at the end
you can even omit the message in this case as it is the only assertion in the test case, which has a description

File: packages/pnpm/src/main.ts (hunk 1 above)
Comment (zkochan) [reply packages/pnpm/src/main.ts]: actually, my proposed solution is also bad because it will return a bad index in case like `pnpm run test --foo -- --flag=true`

Comment (zkochan) [reply packages/pnpm/src/main.ts]: Seems like the right solution is to pass the raw argv to npm when the commands are passed through to npm

**Comment by zkochan** [comment]
ok, I think I figured it out. I'll push a fix and I'll use your test
