### PR TITLE
fix: sync `--allow-build` flag value to `allowBuilds`

### LINKED ISSUE #10339: `--allow-build=<pkg>` flag should write to preferred `allowBuilds` setting
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

_No response_

### Which area(s) of pnpm are affected? (leave empty if unsure)

_No response_

### Link to the code that reproduces this issue or a replay of the bug

_No response_

### Reproduction steps

1. Run `pnpm add` with the `--allow-build=<pkg>` flag
2. Observe that [the non-preferred `onlyBuiltDependencies` setting](https://pnpm.io/settings#onlybuiltdependencies) is written to in `pnpm-workspace.yaml` 💥

```bash
➜  a git:(main) ✗ pnpm add --save-dev eslint-config-upleveled --allow-build=unrs-resolver

...

devDependencies:
+ eslint-config-upleveled ^9.4.2

...

node_modules/unrs-resolver: Running postinstall script, done in 237ms
Done in 7.4s using pnpm v10.26.1

➜  a git:(main) ✗ cat pnpm-workspace.yaml
onlyBuiltDependencies:
  - unrs-resolver
```

### Describe the Bug

The `pnpm add` [`--allow-build=<pkg>` flag](https://pnpm.io/cli/add#--allow-build) (implemented in [PR 9086](https://github.com/pnpm/pnpm/pull/9086)) writes lines in `pnpm-workspace.yaml` to [the non-preferred `onlyBuiltDependencies` setting](https://pnpm.io/settings#onlybuiltdependencies) instead of [the preferred `allowBuilds` setting](https://pnpm.io/blog/releases/10.26#allowbuilds:~:text=This%20replaces%20onlyBuiltDependencies%20and%20ignoredBuiltDependencies%20as%20the%20preferred%20configuration%20method)

### Expected Behavior

`allowBuilds` is used exclusively, because [the pnpm 10.26 blog post](https://pnpm.io/blog/releases/10.26#allowbuilds:~:text=This%20replaces%20onlyBuiltDependencies%20and%20ignoredBuiltDependencies%20as%20the%20preferred%20configuration%20method) mentions that it is the preferred configuration method

> This replaces `onlyBuiltDependencies` and `ignoredBuiltDependencies` as the preferred configuration method

### Which Node.js version are you using?

v24.11.0

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

### PR DESCRIPTION
**Pull request by btea**
close #10339

### CODE REVIEW

File: workspace/manifest-writer/src/index.ts [hunk 1]
```diff
@@ -65,9 +65,11 @@ export async function updateWorkspaceManifest (dir: string, opts: {
     }
 
     // Update allowBuilds instead of the old fields
-    updatedFields.allowBuilds = allowBuilds
-    delete updatedFields.onlyBuiltDependencies
-    delete updatedFields.ignoredBuiltDependencies
+    if (Object.keys(allowBuilds).length > 0) {
```
Comment (zkochan) [inline workspace/manifest-writer/src/index.ts]: Why is this needed? So, now we can't remove all entries from "allowBuilds"?

Comment (btea) [reply workspace/manifest-writer/src/index.ts]: That makes sense; I hadn't considered that situation before.
