### PR TITLE
fix: ensure catalogMode: strict writes version specifier instead of 'catalog:'

### LINKED ISSUE #10176: `catalogMode: strict` creates invalid `pnpm-workspace.yaml`
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

10.21.1

### Which area(s) of pnpm are affected? (leave empty if unsure)

_No response_

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/stefanprobst/issue-pnpm-catalog-strict

### Reproduction steps

- clone the [reproduction repo](https://github.com/stefanprobst/issue-pnpm-catalog-strict)
- `pnpm install`
- see that the `catalog` in `pnpm-workspace.yaml` lists `react: ^19.2.0`
- `cd packages/repro`
- `pnpm add react`
- see that now the `catalog` in `pnpm-workspace.yaml` lists `react: 'catalog:'` not `react: ^19.2.0`

### Describe the Bug

`pnpm add` with `catalogMode: strict` adds "catalog:" instead of a version range to the `catalog` in `pnpm-workspace.yaml`

### Expected Behavior

`pnpm add` with `catalogMode: strict` should always write actual version ranges to `catalog`, not `catalog:` which is circular

### Which Node.js version are you using?

24.11.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [x] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

ubuntu

### PR DESCRIPTION
**Pull request by kairosci**
fix #10176

## Problem

When using `catalogMode: strict`, `pnpm update` or installation commands would sometimes write the literal string `"catalog:"` into `pnpm-workspace.yaml` instead of the resolved version number.

For example, running `pnpm update` would result in:

```yaml
# pnpm-workspace.yaml (incorrect)
catalogs:
  default:
    lodash: 'catalog:'  # Should be the actual version like '^4.17.21'
```

## Root Cause

In `/pkg-manager/resolve-dependencies/src/index.ts`, when building `updatedCatalogs`, the code would use `dep.normalizedBareSpecifier` which could be `undefined` for certain dependency types. The fallback was to use `dep.wantedDependency.bareSpecifier` which contained the literal `'catalog:'` string.

## Solution

Per maintainer's suggestion (@gluxon), instead of falling back to a potentially incorrect value, we now skip adding the dependency to `updatedCatalogs` when `normalizedBareSpecifier` is undefined. The catalog snapshot is already handled correctly in `getCatalogSnapshots.ts`, so skipping here avoids writing incorrect values.

## Changes

- Skip adding to `updatedCatalogs` when `dep.normalizedBareSpecifier` is undefined
- Added regression test to verify the fix
- Added changeset

## Test

The test verifies that after `pnpm update` with `catalogMode: strict`, the `pnpm-workspace.yaml` contains the actual version specifier (e.g., `^4.17.21`) instead of `catalog:`.

### CODE REVIEW

File: pkg-manager/resolve-dependencies/src/index.ts [hunk 1]
```diff
@@ -290,7 +290,12 @@ export async function resolveDependencies (
       if (dep.catalogLookup == null) continue
       updatedCatalogs ??= {}
       updatedCatalogs[dep.catalogLookup.catalogName] ??= {}
-      updatedCatalogs[dep.catalogLookup.catalogName][dep.alias] = dep.normalizedBareSpecifier ?? dep.catalogLookup.userSpecifiedBareSpecifier
+      const spec = dep.normalizedBareSpecifier ?? dep.catalogLookup.specifier
+      if (spec.startsWith('catalog:')) {
+        updatedCatalogs[dep.catalogLookup.catalogName][dep.alias] = dep.version
+      } else {
+        updatedCatalogs[dep.catalogLookup.catalogName][dep.alias] = spec
+      }
```
Comment (gluxon) [inline pkg-manager/resolve-dependencies/src/index.ts]: This fix feels like a workaround. Do you know why the `normalizedBareSpecifier` contains `catalog:` in the first place? That feels like the bug we should fix instead.

Comment (kairosci) [reply pkg-manager/resolve-dependencies/src/index.ts]: I forgot to mark the PR as a draft. 

It seems that during the resolution phase, the protocol isn't being correctly stripped away, leading to this 'leaking' into the writing logic.

I will investigate the resolution/normalization flow to find where the prefix is being incorrectly preserved and fix it there, rather than just filtering it out at the end.

I'll update the PR as soon as I find the root cause in the normalization logic.

Comment (gluxon) [reply pkg-manager/resolve-dependencies/src/index.ts]: Awesome. Thanks so much! 😊

File: pkg-manager/resolve-dependencies/src/index.ts [hunk 2]
```diff
@@ -290,7 +290,10 @@ export async function resolveDependencies (
       if (dep.catalogLookup == null) continue
       updatedCatalogs ??= {}
       updatedCatalogs[dep.catalogLookup.catalogName] ??= {}
-      updatedCatalogs[dep.catalogLookup.catalogName][dep.alias] = dep.normalizedBareSpecifier ?? dep.catalogLookup.userSpecifiedBareSpecifier
+      // Use normalizedBareSpecifier if available, otherwise fall back to the catalog's resolved specifier.
+      // We must NOT use userSpecifiedBareSpecifier here as it contains 'catalog:' which would create
+      // an invalid recursive catalog entry.
+      updatedCatalogs[dep.catalogLookup.catalogName][dep.alias] = dep.normalizedBareSpecifier ?? dep.catalogLookup.specifier
```
Comment (gluxon) [inline pkg-manager/resolve-dependencies/src/index.ts]: Ah, this fix makes a lot of sense. Thank you for explaining.

I've seen the `?? dep.catalogLookup.userSpecifiedBareSpecifier` fallback a few times and knew it was wrong (I wasn't the original author of this line), but didn't think it was a problem since `dep.normalizedBareSpecifier` should be defined most of the time. I also meant to put up a fix for this, but it was lower on my priority list since I didn't think it could cause a real bug. Thank you for finding this.

Small suggestion — Could we modify this fix slightly? Instead of falling back to `dep.catalogLookup.specifier`, could we omit an entry in `updatedCatalogs`? I think that's slightly clearer since we're then saying "_this catalog entry wasn't updated, so don't add it to updatedCatalogs_".

```ts
if (dep.catalogLookup == null) continue

// If normalizedBareSpecifier isn't defined, this catalog entry was resolved from cache.
/ /Avoid updating the updatedCatalogs map since it is likely unchanged.
if (dep.normalizedBareSpecifier == null) continue
```

Unfortunately this fix is still prone to bugs where the resolved catalog was actually changed/updated, but some resolver forgot to populate `normalizedBareSpecifier`. But it's definitely more correct than the code as currently written though, so I think we should proceed with this change.

If you're curious, the `updatedCatalogs` map is eventually passed into a function here that performs a similar fallback:

https://github.com/pnpm/pnpm/blob/facd7656e8b44cf1744e6f656546deab58a62384/pkg-manager/resolve-dependencies/src/getCatalogSnapshots.ts#L21

File: pkg-manager/resolve-dependencies/src/index.ts [hunk 3]
```diff
@@ -466,7 +469,7 @@ function extendGraph (
     enableGlobalVirtualStore?: boolean
   }
 ): DependenciesGraph {
-  const pkgMetaIter = (function * () {
+  const pkgMetaIter = (function* () {
```
Comment (gluxon) [inline pkg-manager/resolve-dependencies/src/index.ts]: nitpick: Could existing formatting be kept the same?

File: pkg-manager/resolve-dependencies/src/index.ts [hunk 4]
```diff
@@ -331,7 +334,7 @@ export async function resolveDependencies (
     await Promise.all(Object.values(resolvedPkgsById).map(async ({ fetching }) => {
       try {
         await fetching?.()
-      } catch {}
+      } catch { }
```
Comment (gluxon) [inline pkg-manager/resolve-dependencies/src/index.ts]: nitpick: Could existing formatting be kept the same?

File: pkg-manager/resolve-dependencies/src/index.ts (hunk 2 above)
Comment (kairosci) [reply pkg-manager/resolve-dependencies/src/index.ts]: First of all, thank you for the explanation!
Secondly, I would say that your idea seems better than mine; I hadn't thought of that.

If normalizedBareSpecifier is not defined, updatedCatalogs remains unchanged. 
The fallback to specifier is still handled within getCatalogSnapshots.ts.

Comment (gluxon) [reply pkg-manager/resolve-dependencies/src/index.ts]: You're welcome! Thanks in turn for discovering this fallback could actually cause real problems. I was mistaken about that.
