### PR TITLE
fix: add support for npm lockfile v3 in `import`

### LINKED ISSUE #6233: pnpm import completely ignores package-lock.json files
[pnpm import](https://pnpm.io/cli/install) says it should work with a package-lock.json, however it seems to be **completely ignoring it**, there's no difference between doing a `pnpm import` and a `pnpm i --lockfile-only`.

Example:

package.json
```
{
  "name": "pnpmfail",
  "version": "0.0.0",
  "license": "UNLICENSED",
  "dependencies": {
    "@algolia/transporter": "^4.13.1"
  }
}
```

package-lock.json:
```
{
  "name": "pnpmfail",
  "version": "0.0.0",
  "lockfileVersion": 3,
  "requires": true,
  "packages": {
    "": {
      "name": "pnpmfail",
      "version": "0.0.0",
      "license": "UNLICENSED",
      "dependencies": {
        "@algolia/transporter": "^4.13.1"
      }
    },
    "node_modules/@algolia/cache-common": {
      "version": "4.14.3",
      "resolved": "https://registry.npmjs.org/@algolia/cache-common/-/cache-common-4.14.3.tgz",
      "integrity": "sha512-oZJofOoD9FQOwiGTzyRnmzvh3ZP8WVTNPBLH5xU5JNF7drDbRT0ocVT0h/xB2rPHYzOeXRrLaQQBwRT/CKom0Q=="
    },
    "node_modules/@algolia/logger-common": {
      "version": "4.14.3",
      "resolved": "https://registry.npmjs.org/@algolia/logger-common/-/logger-common-4.14.3.tgz",
      "integrity": "sha512-kUEAZaBt/J3RjYi8MEBT2QEexJR2kAE2mtLmezsmqMQZTV502TkHCxYzTwY2dE7OKcUTxi4OFlMuS4GId9CWPw=="
    },
    "node_modules/@algolia/requester-common": {
      "version": "4.14.3",
      "resolved": "https://registry.npmjs.org/@algolia/requester-common/-/requester-common-4.14.3.tgz",
      "integrity": "sha512-RrRzqNyKFDP7IkTuV3XvYGF9cDPn9h6qEDl595lXva3YUk9YSS8+MGZnnkOMHvjkrSCKfoLeLbm/T4tmoIeclw=="
    },
    "node_modules/@algolia/transporter": {
      "version": "4.14.3",
      "resolved": "https://registry.npmjs.org/@algolia/transporter/-/transporter-4.14.3.tgz",
      "integrity": "sha512-2qlKlKsnGJ008exFRb5RTeTOqhLZj0bkMCMVskxoqWejs2Q2QtWmsiH98hDfpw0fmnyhzHEt0Z7lqxBYp8bW2w==",
      "dependencies": {
        "@algolia/cache-common": "4.14.3",
        "@algolia/logger-common": "4.14.3",
        "@algolia/requester-common": "4.14.3"
      }
    }
  }
```

I run the command: `pnpm import`

Generated pnpm-lock.yaml
```
lockfileVersion: 5.4

specifiers:
  '@algolia/transporter': ^4.13.1

dependencies:
  '@algolia/transporter': 4.15.0

packages:

  /@algolia/cache-common/4.15.0:
    resolution: {integrity: sha512-Me3PbI4QurAM+3D+htIE0l1xt6+bl/18SG6Wc7bPQEZAtN7DTGz22HqhKNyLF2lR/cOfpaH7umXZlZEhIHf7gQ==}
    dev: false

  /@algolia/logger-common/4.15.0:
    resolution: {integrity: sha512-D8OFwn/HpvQz66goIcjxOKsYBMuxiruxJ3cA/bnc0EiDvSA2P2z6bNQWgS5gbstuTZIJmbhr+53NyOxFkmMNAA==}
    dev: false

  /@algolia/requester-common/4.15.0:
    resolution: {integrity: sha512-w0UUzxElbo4hrKg4QP/jiXDNbIJuAthxdlkos9nS8KAPK2XI3R9BlUjLz/ZVs4F9TDGI0mhjrNHhZ12KXcoyhg==}
    dev: false

  /@algolia/transporter/4.15.0:
    resolution: {integrity: sha512-JoWR+ixG3EmA0UPntQFN/FV5TasYcYu93d5+oKzHFeZ6Z7rtW5Im9iy/Oh/ggk1AAN5fTdqKewtbBpdaYDbKsQ==}
    dependencies:
      '@algolia/cache-common': 4.15.0
      '@algolia/logger-common': 4.15.0
      '@algolia/requester-common': 4.15.0
    dev: false
```

As you can see, despite the package-lock stating the version installed should have been `4.14.3`, the generated pnpm-lockfile suggests it should resolve to `4.15.0`.

I've also tried specifying the package-lock.json file using `pnpm import package-lock.json` but that had the same effect. It seems as though pnpm just totally ignores any package-lockfile that's already there.

Is there something I'm missing?

### PR DESCRIPTION
**Pull request by nachoaldamav**
closes #6233

### CODE REVIEW

**Review by zkochan — CHANGES_REQUESTED** [review]
Cover this with a test

File: pkg-manager/plugin-commands-installation/src/import/index.ts [hunk 1]
```diff
@@ -246,7 +255,49 @@ function getAllVersionsByPackageNames (
...
+
+    if (pkgDetails.packages) {
+      extractDependencies(versionsByPackageNames, pkgDetails.packages)
+    }
+    if (pkgDetails.dependencies) {
+      for (const [pkgName1, version] of Object.entries(pkgDetails.dependencies)) {
+        if (!versionsByPackageNames[pkgName1]) {
+          versionsByPackageNames[pkgName1] = new Set<string>()
+        }
+        // @ts-expect-error
```
Comment (zkochan) [inline pkg-manager/plugin-commands-installation/src/import/index.ts]: This should be removed

**Review by zkochan — APPROVED** [review]

**Comment by landed1** [comment]
Hi Noob question. I started to use pnpm and now dont have a lock file. This is giving me an error when I try to build on github pages. So I found that the defualt build script provided by Github is not designed for pnpm. So I used AI to get the following:

`# Workflow for building and deploying a Next.js site to GitHub Pages using pnpm
name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"] # Trigger on push to the main branch
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Specify your Node.js version
          cache: pnpm # Cache dependencies for pnpm

      - name: Install pnpm
        run: npm install -g pnpm # Install pnpm globally

      - name: Restore dependencies
        run: pnpm install # Use pnpm to install dependencies

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Build with Next.js
        run: pnpm next build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out # Ensure this matches your Next.js `output` configuration

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
`
This installs the pnpm program so I don't know why it still fails. 

Error : Unable to locate executable file: pnpm. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
