### PR TITLE
fix: improve the error messages related to `trustPolicy` mismatch

### LINKED ISSUE #10202: `no-downgrade` should check the same major version
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

10.22.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver

### Link to the code that reproduces this issue or a replay of the bug

_No response_

### Reproduction steps

> [ERR_PNPM_TRUST_DOWNGRADE] High-risk trust downgrade for "semver@6.3.1" (possible package takeover)
> 
> This error happened while installing the dependencies of @babel/core@7.28.5
> 
> Earlier versions had provenance attestation, but this version has no trust evidence. A trust downgrade may indicate a supply chain incident.

### Describe the Bug

> When set to `no-downgrade`, pnpm will fail if a package's trust level has decreased compared to previous releases.

`semver@6` was never released with provenance. So it isn't a downgrade.

`semver@7` with provenance was [released](https://www.npmjs.com/package/semver?activeTab=versions) before and after `@6.3.1` which seems to be causing the issue.

### Expected Behavior

`no-downgrade` should check the same major version

### Which Node.js version are you using?

24.11.0

### Which operating systems have you used?

- [ ] macOS
- [x] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

### PR DESCRIPTION
**Pull request by btea**
close #10202

### CODE REVIEW

File: resolving/npm-resolver/src/trustChecks.ts [hunk 1]
```diff
@@ -52,7 +52,7 @@ export function failIfTrustDowngraded (
       'TRUST_DOWNGRADE',
       `High-risk trust downgrade for "${meta.name}@${version}" (possible package takeover)`,
       {
-        hint: `Earlier versions had ${prettyPrintTrustEvidence(strongestEvidencePriorToRequestedVersion)}, ` +
+        hint: `Earlier released version(${strongestTrustEvidenceVersion}) had ${prettyPrintTrustEvidence(strongestEvidencePriorToRequestedVersion)}, ` +
```
Comment (ryo-manba) [inline resolving/npm-resolver/src/trustChecks.ts]: Maybe we shouldn't include the specific version number in the message.
Showing something like `semver@7.5.1` while installing `semver@6.3.1` could be confusing.

Thoughts?
```suggestion
        hint: `Previously published releases had ${prettyPrintTrustEvidence(strongestEvidencePriorToRequestedVersion)}, ` +
```

Comment (zkochan) [reply resolving/npm-resolver/src/trustChecks.ts]: I don't think the existing text needs changes. Just add this to the hint:

```
'Trust checks are based solely on publish date, not semver. ' +
          'A package cannot be installed if any earlier-published version had stronger trust evidence.',
```
