### PR TITLE
fix: only automatically resolve optional peers with versions that satisfy the ranges

### LINKED ISSUE #7985: Optional peer dependency cause unmet warning
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

_No response_

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver

### Link to the code that reproduces this issue or a replay of the bug

https://stackblitz.com/edit/vitejs-vite-sttob6

### Reproduction steps

Enter the repro link and run `pnpm v9` (which is a script to install dependencies with v9 instead of default v8 in stackblitz).

### Describe the Bug

The following error will be printed
```
    └─┬ vite-plugin-checker 0.6.4
      └── ✕ unmet peer meow@^9.0.0: found 13.2.0
```

### Expected Behavior

Should not have unmet warning as `meow` is an optional dependency of `vite-plugin-checker`

No warning in pnpm v8

### Which Node.js version are you using?

v20.11.1

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

### PR DESCRIPTION
**Pull request by zkochan**
close #7985

### CODE REVIEW

File: pkg-manager/resolve-dependencies/src/resolveDependencies.ts [hunk 1]
```diff
@@ -358,6 +347,22 @@ export async function resolveRootDependencies (
...
+        const resolveDependenciesResult = await resolveDependencies(ctx, preferredVersions, wantedDependencies, {
+          ...options,
+          parentPkgAliases,
+          publishedBy,
+        })
+        importerResolutionResult = {
+          pkgAddresses: resolveDependenciesResult.pkgAddresses,
+          ...filterMissingPeers(await resolveDependenciesResult.resolvingPeers, parentPkgAliases),
+        }
+        pkgAddresses.push(...importerResolutionResult.pkgAddresses)
```
Comment (gluxon) [inline pkg-manager/resolve-dependencies/src/resolveDependencies.ts:363]: I see this happens above on line 48 too, but I'd be a bit worried about stack overflows here with large arrays. It might be safer to use a for loop since that doesn't have the same downside?

Are we guaranteed `importerResolutionResult.pkgAddresses` is small? I'm guessing it will be 99% of the time, but still depends on user input.

File: pkg-manager/resolve-dependencies/src/hoistPeers.ts [hunk 2]
```diff
@@ -27,3 +27,20 @@ export function hoistPeers (
   }
   return dependencies
 }
+
+export function hoistOptionalPeers (
```
Comment (gluxon) [inline pkg-manager/resolve-dependencies/src/hoistPeers.ts]: nitpick: The name `hoistOptionalPeers` makes me think it'll perform a side-effect. In this case, it looks like it's just a pure function that computes a map. How about `getSatisfyingOptionalPeersFromFullGraph`?

**Review by gluxon — APPROVED** [review]

File: pkg-manager/resolve-dependencies/src/resolveDependencies.ts (hunk 1 above)
Comment (zkochan) [reply pkg-manager/resolve-dependencies/src/resolveDependencies.ts:363]: I am not sure what you mean. How does an array concatenation cause a stackoverflow?

Comment (gluxon) [reply pkg-manager/resolve-dependencies/src/resolveDependencies.ts:363]: Sorry, I should have cited something. The best discussion of the issue I can find is:

https://github.com/nodejs/node/issues/16870

The problem is that all arguments are placed onto the stack one by one before calling `.push`, which means that this code can throw depending on how deep in the stack we are already and argument size.

I tend to avoid spreading arguments into a function if the arguments aren't a fixed size so I don't have to think about this problem.

File: pkg-manager/resolve-dependencies/src/hoistPeers.ts (hunk 2 above)
Comment (Ciornenichii) [reply pkg-manager/resolve-dependencies/src/hoistPeers.ts]: 👏

File: pkg-manager/resolve-dependencies/src/resolveDependencies.ts (hunk 1 above)
Comment (zkochan) [reply pkg-manager/resolve-dependencies/src/resolveDependencies.ts:363]: oh wow, good to know
