### PR TITLE
fix: cannot set property name of which has only a getter

### LINKED ISSUE #5572: TypeError: Cannot set property name of  which has only a getter
### Additional information:

 - `node -v` prints:
 - Windows, macOS, or Linux?:

### PR DESCRIPTION
**Pull request by zkochan**
close #5572

### CODE REVIEW

File: packages/pnpm/src/err.ts [hunk 1]
```diff
@@ -11,7 +11,11 @@ export function errorHandler (error: Error) {
     return
   }
   if (error.name != null && error.name !== 'pnpm' && !error.name.startsWith('pnpm:')) {
-    error.name = 'pnpm'
+    try {
+      error.name = 'pnpm'
+    } catch {
+      // Sometimes the name property is read-only
+    }
```
Comment (lvqq) [inline packages/pnpm/src/err.ts:18]: I think this change can also be merged to v6 branch since there has a similar issue: https://github.com/pnpm/pnpm/issues/4270

**Review by lvqq — APPROVED** [review]

File: packages/pnpm/src/err.ts (hunk 1 above)
Comment (zkochan) [reply packages/pnpm/src/err.ts:18]: oh, wow
