### PR TITLE
fix: give warning instead of error when dependency has an empty bin field

### LINKED ISSUE #2293: Installation of dependency should not fail if it has an empty bin field
This is a regression introduced by #2284

If a package has an empty bin, a warning should be printed.

For printing a warning, `@pnpm/logger` can be used. `logger.warn()`

### PR DESCRIPTION
**Pull request by yaodingyd**
Close #2293

### CODE REVIEW

File: packages/link-bins/src/index.ts [hunk 1]
```diff
@@ -122,7 +123,10 @@ async function getPackageBins (
   }
 
   if (R.isEmpty(pkg.bin)) {
-    throw new PnpmError('INVALID_PACKAGE_BIN', `Package in ${target} must have a non-empty bin field to get bin linked.`)
+    logger.warn({
```
Comment (zkochan) [inline packages/link-bins/src/index.ts]: I was not right. In this case don't use `@pnpm/logger`. Use the warn function passed in with opts.

Comment (zkochan) [reply packages/link-bins/src/index.ts]: that will also allow you to test it easily
