### PR TITLE
fix: issues with storybook and the new lockfile format

### LINKED ISSUE #5976: storybook production build breaks with `use-lockfile-v6`
### Code to reproduce the issue:

We recently updated to the new `use-lockfile-v6` format and everything works fine except our storybook production build.

This is the stacktrace:

```
$ nx run zorro-ui-design:build-storybook               

> nx run zorro-ui-design:build-storybook


>  NX  ui framework: @storybook/react


>  NX  Storybook builder starting ...

info => Cleaning outputDir: /home/user/Webdevelopment/Freelancing/org/repo/dist/storybook/zorro-ui-design

 >  NX   Cannot copy `/home/user/Webdevelopment/Freelancing/org/repo/node_modules/.pnpm/@storybook+core-server@6.5.15(@storybook+builder-w_2rbwioi6ggwys4pddb257x4q6a/node_modules/@storybook/core-server/public/favicon.ico`: the file doesn't exist

   Pass --verbose to see the stacktrace.


 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build-storybook for project repo (8s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

I have also reported this issue on https://github.com/storybookjs/storybook/issues/20673 since I am not sure which repo has to make changes here to make it work.

### Expected behavior:

Storybook production build should work same as before

### Actual behavior:

The build runs into "file not found" issues with favicon.ico and then probably other files as well.

### Additional information:

 - `node -v` prints: 18.12.1
 - Windows, macOS, or Linux?: Ubuntu 22.10

### PR DESCRIPTION
**Pull request by zkochan**
close #5976

### CODE REVIEW

**Review by bvanjoi — APPROVED** [review]

File: packages/dependency-path/src/index.ts [hunk 1]
```diff
@@ -143,7 +143,13 @@ export function parse (dependencyPath: string) {
 }
 
 export function depPathToFilename (depPath: string) {
-  const filename = depPathToFilenameUnescaped(depPath).replace(/[\\/:*?"<>|]/g, '+')
+  let filename = depPathToFilenameUnescaped(depPath).replace(/[\\/:*?"<>|]/g, '+')
+  if (filename.includes('(')) {
+    filename = filename
+      .replace(/\)\(/g, '_')
+      .replace(/\(/, '_')
```
Comment (await-ovo) [inline packages/dependency-path/src/index.ts]: should this be `.replace(/\(/g, '_')` also? Then this can be simplified to `filename.replace(/(\)\()|\(/g, '_')`

Comment (zkochan) [reply packages/dependency-path/src/index.ts]: done

**Review by await-ovo — APPROVED** [review]
