### PR TITLE
fix: update choice list not show deprecated pkg

### LINKED ISSUE #9206: pnpm update lists packages with no version changes
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

_No response_

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

_No response_

### Reproduction steps

using `pnpm update --interactive --recursive --latest`

### Describe the Bug

```bash
❯ pnpm update --interactive --recursive --latest
? Choose which packages to update (Press <space> to select, <a> to toggle all, <i> to invert selection) …
❯ ○ devDependencies
    ○ Package                                                    Current   Target            Workspace   URL
    ○ @swc/core                                                   1.11.1 ❯ 1.11.5            x
    ○ @types/eventsource                                           3.0.0 ❯ 3.0.0             x
    ○ @types/node                                               20.17.19 ❯ 22.13.8           x
    ○ prettier                                                     3.5.2 ❯ 3.5.3             x
    ○ typescript                                                   5.7.3 ❯ 5.8.2             x

Enter to start updating. Ctrl-c to cancel.
```

Note `@types/eventsource` current and target versions are the same.

```yml
'@types/eventsource@3.0.0':
    resolution: {integrity: sha512-yEhFj31FTD29DtNeqePu+A+lD6loRef6YOM5XfN1kUwBHyy2DySGlA3jJU+FbQSkrfmlBVluf2Dub/OyReFGKA==}
    deprecated: This is a stub types definition. eventsource provides its own type definitions, so you do not need this installed.
```

Even choosing it to upgrade doesn't make any changes.

### Expected Behavior

Not listing packages that have no update

### Which Node.js version are you using?

v20.18.3

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

### PR DESCRIPTION
**Pull request by btea**
A deprecation mark is added based on the original logic to prompt the user.

close #9206

### CODE REVIEW

**Comment by zkochan** [comment]
So the update command will still list the packages that don't have newer versions but print the "(deprecated)" label?

**Comment by btea** [comment]
No, the newer version will be shown in the list, and the `deprecated` label will be added, as shown below:

image

**Comment by zkochan** [comment]
The added deprecated label sounds good. 

but I think we shouldn't list those dependencies that don't have newer versions.

**Comment by btea** [comment]
Remove the judgment ` || latestManifest.deprecated` here?
https://github.com/pnpm/pnpm/blob/cd8caece258e154274c2feb4d6dab3293cb8bc21/reviewing/outdated/src/outdated.ts#L176

**Comment by zkochan** [comment]
This is also used by the outdated command, I believe. Maybe for outdated it should remain but of update it should be filtered out

**Comment by btea** [comment]
OK, I have filtered it.

File: pkg-manager/plugin-commands-installation/src/update/getUpdateChoices.ts [hunk 1]
```diff
@@ -48,8 +48,8 @@ export function getUpdateChoices (outdatedPkgsOfProjects: OutdatedPackage[], wor
   const finalChoices: ChoiceGroup = []
   for (const [depGroup, choiceRows] of Object.entries(groupPkgsByType)) {
     if (choiceRows.length === 0) continue
-
-    const rawChoices = choiceRows.map(choice => buildPkgChoice(choice, workspacesEnabled))
+    const rawChoices = choiceRows.filter(choice => !choice.latestManifest?.deprecated).map(choice => buildPkgChoice(choice, workspacesEnabled))
```
Comment (zkochan) [inline pkg-manager/plugin-commands-installation/src/update/getUpdateChoices.ts]: but won't this also filter out those that have a new version that is deprecated? We should filter out those that have the same version

Comment (btea) [reply pkg-manager/plugin-commands-installation/src/update/getUpdateChoices.ts]: Indeed, it has been updated.

**Review by zkochan — APPROVED** [review]

**Comment by MoKhajavi75** [comment]
I reported this and it got fixed in less than 5 days!
Just wanted to say thanks for your dedicated hard efforts!
