### PR TITLE
fix(requireHooks): grabs hooks from workspacePrefix

### LINKED ISSUE #1863: pnpm install in workspace folder doesn't respect pnpmfile
### Code to reproduce the issue:
https://github.com/johnroot/pnpmfile-repro

### Expected behavior:
While in a workspace, `pnpm install` should respect the `pnpmfile` of that workspace.

### Actual behavior:
`pnpm install` (and other commands) does not respect the `pnpm` file of a workspace. However, `pnpm recursive install` does. ~~`pnpm install --pnpmfile=../../pnpmfile.js` does not work either.~~ 

### Additional information:

 - `node -v` prints: v11.14.0
 - Windows, OS X, or Linux?: Windows

### PR DESCRIPTION
**Pull request by johnroot**
fix #1863. change requireHooks to load pnpmfile from workspacePrefix if it exists. In non-recursive installations, the pnpmfile in a package is preferred over the workspace root

### CODE REVIEW

File: packages/pnpm/test/recursive/misc.ts [hunk 1]
```diff
@@ -360,6 +361,53 @@ test('recursive installation of packages with hooks', async t => {
   t.ok(lockfile2.packages['/dep-of-pkg-with-1-dep/100.1.0'])
 })
 
+test('recursive installation of packages in workspace ignores hooks in package', async t => {
+  // This test hangs on Appveyor for some reason
+  if (isCI && isWindows()) return
```
Comment (johnroot) [inline packages/pnpm/test/recursive/misc.ts:338]: I copied the framework for these tests from a test that had this check; I'm unsure if it'll apply to the tests I wrote to I put it in one and not the other.

File: packages/pnpm/test/recursive/misc.ts [hunk 2]
```diff
@@ -360,6 +361,53 @@ test('recursive installation of packages with hooks', async t => {
...
+    function readPackage (pkg) {
+      pkg.dependencies = pkg.dependencies || {}
+      pkg.dependencies['dep-of-pkg-with-1-dep'] = '100.1.0'
+      return pkg
+    }
+  `
+  await fs.writeFile('pnpmfile.js', pnpmfile, 'utf8')
+
+  process.chdir('../project-2')
+  await fs.writeFile('pnpmfile.js', pnpmfile, 'utf8')
```
Comment (zkochan) [inline packages/pnpm/test/recursive/misc.ts:370]: why don't you also add a pnpmfile in the root of the workspace to see that is ignored as well?

File: packages/pnpm/src/requireHooks.ts [hunk 3]
```diff
@@ -9,13 +9,15 @@ export default function requireHooks (
...
+    workspacePrefix?: string,
     pnpmfile?: string,
   },
 ) {
   const globalPnpmfile = opts.globalPnpmfile && requirePnpmfile(pathAbsolute(opts.globalPnpmfile, prefix), prefix)
   let globalHooks = globalPnpmfile && globalPnpmfile.hooks
 
-  const pnpmFile = opts.pnpmfile && requirePnpmfile(pathAbsolute(opts.pnpmfile, prefix), prefix)
+  const pnpmFile = (opts.pnpmfile && requirePnpmfile(pathAbsolute(opts.pnpmfile, prefix), prefix))
+    || (opts.workspacePrefix && requirePnpmfile(path.join(opts.workspacePrefix, 'pnpmfile.js'), prefix))
```
Comment (zkochan) [inline packages/pnpm/src/requireHooks.ts]: I think I would expect this to be the last checked pnpmfile

File: packages/pnpm/test/recursive/misc.ts (hunk 2 above)
Comment (johnroot) [reply packages/pnpm/test/recursive/misc.ts:370]: Not 100% sure what you meant by this; tried to clarify the tests to more clearly test the behavior.

**Comment by zkochan** [comment]
I realized, that the pnpmfile should be located in the same folder where the lockfile is, so in lockfileDirectory. I pushed this change to your branch.

One test is failing. I'll look into it and then merge.

Thanks for your contribution!
