### PR TITLE
fix: don't write `pnpm-lock.yaml` if it has no changes

### LINKED ISSUE #6158: `pnpm install --frozen-lockfile` updates modified time of  `pnpm-lock.yaml` and root dir each time it runs even without changes
### Code to reproduce the issue:

It happens in any project regardless of packages in it. `package.json` has only `rimraf` as a dependency.
```
~/Projects/pnpm-bug-report
➞  stat pnpm-lock.yaml
16777220 104927827 -rw-r--r-- 1 artur_ptaszek staff 0 296 "Mar  1 15:13:12 2023" "Mar  1 15:13:11 2023" "Mar  1 15:13:11 2023" "Mar  1 15:13:11 2023" 4096 8 0 pnpm-lock.yaml

~/Projects/pnpm-bug-report
➞  pnpm install --frozen-lockfile
Lockfile is up to date, resolution step is skipped
Already up to date
Done in 393ms

~/Projects/pnpm-bug-report
➞  stat pnpm-lock.yaml
16777220 104927846 -rw-r--r-- 1 artur_ptaszek staff 0 296 "Mar  1 15:13:26 2023" "Mar  1 15:13:24 2023" "Mar  1 15:13:24 2023" "Mar  1 15:13:24 2023" 4096 8 0 pnpm-lock.yaml
```

### Expected behavior:
If `pnpm` reponse with `Already up to date`, then shouldn't affect both root catalog and `pnpm-lock.yaml` in any kind.

### Actual behavior:
`pnpm install --frozen-lockfile` updates modified time of  `pnpm-lock.yaml` and root dir each time it runs even without changes.

### Additional information:

 - `node -v` prints: v18.14.0
 - Windows, macOS, or Linux?: macOS

### PR DESCRIPTION
**Pull request by zkochan**
close #6158

### CODE REVIEW

**Review by kenrick95 — APPROVED** [review]

File: pkg-manager/headless/src/index.ts [hunk 1]
```diff
@@ -545,7 +546,7 @@ export async function headlessInstall (opts: HeadlessOptions) {
       storeDir: opts.storeDir,
       virtualStoreDir,
     })
-    if (opts.useLockfile) {
+    if (opts.useLockfile && JSON.stringify(wantedLockfile) !== JSON.stringify(opts.wantedLockfileUnmodified)) {
```
Comment (gluxon) [inline pkg-manager/headless/src/index.ts]: nit: It might be worth following up with a `deepEqual(...)` function that early exits as soon as it sees the lockfiles are different for performance. I've seen `pnpm-lock.yaml` files grow to be 4MB, and serializing 2 * 4MB could add a few seconds to each `pnpm install`.

File: pkg-manager/get-context/src/readLockfiles.ts [hunk 2]
```diff
@@ -128,6 +129,7 @@ export async function readLockfiles (
     existsCurrentLockfile: files[1] != null,
     existsWantedLockfile: files[0] != null && !isEmptyLockfile(wantedLockfile),
     wantedLockfile,
+    wantedLockfileUnmodified: JSON.parse(JSON.stringify(wantedLockfile)),
```
Comment (gluxon) [inline pkg-manager/get-context/src/readLockfiles.ts]: nit: It might be worth a comment that we have to recreate this object since the consumer is expected to mutate `wantedLockfile`. But maybe that's fairly obvious and isn't worth commenting.

**Review by gluxon — APPROVED** [review]
Thanks!

File: pkg-manager/get-context/src/readLockfiles.ts (hunk 2 above)
Comment (zkochan) [reply pkg-manager/get-context/src/readLockfiles.ts]: I was also considering just to save the hash of the object and then comparing hashes. That would use less memory but probably would do more processing

File: pkg-manager/headless/src/index.ts (hunk 1 above)
Comment (zkochan) [reply pkg-manager/headless/src/index.ts]: I have changed it. There was actually no need in the copy.

File: pkg-manager/get-context/src/readLockfiles.ts (hunk 2 above)
Comment (zkochan) [reply pkg-manager/get-context/src/readLockfiles.ts]: I have changed it. There was actually no need in the copy.

File: pkg-manager/headless/src/index.ts (hunk 1 above)
Comment (gluxon) [reply pkg-manager/headless/src/index.ts]: Nice!
