### PR TITLE
fix: don't fetch tarballs when lockfile-only install is run

### LINKED ISSUE #1328: The "--lockfile-only" flag still downloads the full tarball for every dependency
### Code to reproduce the issue:

Run `pnpm install --shrinkwrap-only`.

My understanding was that this feature allows people to update their **shrinkwrap.yaml** file very quickly, in situations where they aren't going to be building anything locally, so they don't need their **node_modules** folder to be updated.  (For example, I'm going to push the updated **shrinkwrap.yaml** to a PR branch, and I optimistically expect the PR build to succeed, so there's no reason to build it locally.)

### Expected behavior:

Run `pnpm install --shrinkwrap-only` runs very quickly.

### Actual behavior:

Run `pnpm install --shrinkwrap-only` takes about the same amount of time as a regular `pnpm install --shrinkwrap-only`.

If that's by design, perhaps we should deprecate the `--shrinkwrap-only` flag?  Or perhaps I am misunderstanding its purpose?

### Additional information:

This is apparently a recent regression due to the work with corgi headers.  See @nickpape-msft 's comments on https://github.com/pnpm/pnpm/pull/1177#issuecomment-413724593 for background.

 - `node -v` prints: 8.9.4
 - Windows, OS X, or Linux?: Windows

### PR DESCRIPTION
**Pull request by zkochan**
close #1328

### CODE REVIEW

File: pkg-manager/resolve-dependencies/src/resolveDependencies.ts [hunk 1]
```diff
@@ -1083,6 +1083,9 @@ async function resolveDependency (
     }
   }
   try {
+    if (!options.update && currentPkg.version) {
+      wantedDependency.pref = currentPkg.version
+    }
```
Comment (zkochan) [inline pkg-manager/resolve-dependencies/src/resolveDependencies.ts]: This will only work with packages from the npm registry (not from github etc). Maybe if we would save the pref as the package id in the lockfile, we could solve it for all.
