### PR TITLE
fix: prevent table width error in `pnpm outdated --long`

### LINKED ISSUE #10040: Invalid config when running `pnpm outdated --long` after updating to 10.18.0 (via corepack)
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

v10.18.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/FabienDehopre/dehopre.dev/tree/pnpm-10.18-issue

### Reproduction steps

- update pnpm to v10.18.0 using corepack: `corepack use pnpm@10.18.0`
- run `pnpm outdated --long`

### Describe the Bug

After updating pnpm to v10.18.0 via corepack, the command "pnpm outdated --long" fails to execute with the following output:
```shell
config {
  border: {
    topBody: '\x1B[90m─\x1B[39m',
    topJoin: '\x1B[90m┬\x1B[39m',
    topLeft: '\x1B[90m┌\x1B[39m',
    topRight: '\x1B[90m┐\x1B[39m',
    bottomBody: '\x1B[90m─\x1B[39m',
    bottomJoin: '\x1B[90m┴\x1B[39m',
    bottomLeft: '\x1B[90m└\x1B[39m',
    bottomRight: '\x1B[90m┘\x1B[39m',
    bodyJoin: '\x1B[90m│\x1B[39m',
    bodyLeft: '\x1B[90m│\x1B[39m',
    bodyRight: '\x1B[90m│\x1B[39m',
    joinBody: '\x1B[90m─\x1B[39m',
    joinJoin: '\x1B[90m┼\x1B[39m',
    joinLeft: '\x1B[90m├\x1B[39m',
    joinRight: '\x1B[90m┤\x1B[39m'
  },
  columns: { '3': { width: 0, wrapWord: true } }
}
errors [
  {
    message: 'must be >= 1',
    params: { comparison: '>=', limit: 1 },
    schemaPath: '#/properties/width/minimum'
  },
  {
    message: 'must be array',
    params: { type: 'array' },
    schemaPath: '#/oneOf/1/type'
  },
  {
    message: 'must match exactly one schema in oneOf',
    params: { passingSchemas: null },
    schemaPath: '#/oneOf'
  }
]
 ERROR  Invalid config.

pnpm: Invalid config.
    at validateConfig (/Users/fabien/.cache/node/corepack/v1/pnpm/10.18.0/dist/pnpm.cjs:132591:15)
    at makeTableConfig (/Users/fabien/.cache/node/corepack/v1/pnpm/10.18.0/dist/pnpm.cjs:133256:43)
    at table (/Users/fabien/.cache/node/corepack/v1/pnpm/10.18.0/dist/pnpm.cjs:133344:60)
    at renderOutdatedTable (/Users/fabien/.cache/node/corepack/v1/pnpm/10.18.0/dist/pnpm.cjs:185635:32)
    at Object.handler [as outdated] (/Users/fabien/.cache/node/corepack/v1/pnpm/10.18.0/dist/pnpm.cjs:185585:20)
    at async /Users/fabien/.cache/node/corepack/v1/pnpm/10.18.0/dist/pnpm.cjs:199870:23
    at async main (/Users/fabien/.cache/node/corepack/v1/pnpm/10.18.0/dist/pnpm.cjs:199828:34)
    at async runPnpm (/Users/fabien/.cache/node/corepack/v1/pnpm/10.18.0/dist/pnpm.cjs:200095:5)
    at async /Users/fabien/.cache/node/corepack/v1/pnpm/10.18.0/dist/pnpm.cjs:200087:7
````

The command "pnpm outdated" (without the `--long` flag) works as expected.

### Expected Behavior

should display the the table with the repo link without issue (as previous version does)
```shell
┌─────────────────────────────────────┬─────────┬────────┬───────────────────────────────────────────────────────────────────────────┐
│ Package                             │ Current │ Latest │ Details                                                                   │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ @analogjs/vite-plugin-angular (dev) │ 1.21.1  │ 1.21.2 │ https://github.com/analogjs/analog#readme                                 │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ @analogjs/vitest-angular (dev)      │ 1.21.1  │ 1.21.2 │ https://analogjs.org                                                      │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ @angular-devkit/build-angular (dev) │ 20.3.3  │ 20.3.4 │ https://github.com/angular/angular-cli                                    │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ @angular-devkit/core (dev)          │ 20.3.3  │ 20.3.4 │ https://github.com/angular/angular-cli                                    │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ @angular-devkit/schematics (dev)    │ 20.3.3  │ 20.3.4 │ https://github.com/angular/angular-cli                                    │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ @angular/build (dev)                │ 20.3.3  │ 20.3.4 │ https://github.com/angular/angular-cli                                    │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ @angular/cli (dev)                  │ 20.3.3  │ 20.3.4 │ https://github.com/angular/angular-cli                                    │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ @angular/ssr                        │ 20.3.3  │ 20.3.4 │ https://github.com/angular/angular-cli                                    │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ @schematics/angular (dev)           │ 20.3.3  │ 20.3.4 │ https://github.com/angular/angular-cli                                    │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ vite (dev)                          │ 7.1.8   │ 7.1.9  │ https://vite.dev                                                          │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ @nx/angular (dev)                   │ 21.5.2  │ 21.6.3 │ https://nx.dev                                                            │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ @nx/devkit (dev)                    │ 21.5.2  │ 21.6.3 │ https://nx.dev                                                            │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ @nx/eslint (dev)                    │ 21.5.2  │ 21.6.3 │ https://nx.dev                                                            │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ @nx/eslint-plugin (dev)             │ 21.5.2  │ 21.6.3 │ https://nx.dev                                                            │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ @nx/js (dev)                        │ 21.5.2  │ 21.6.3 │ https://nx.dev                                                            │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ @nx/playwright (dev)                │ 21.5.2  │ 21.6.3 │ https://nx.dev                                                            │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ @nx/vite (dev)                      │ 21.5.2  │ 21.6.3 │ https://nx.dev                                                            │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ @nx/web (dev)                       │ 21.5.2  │ 21.6.3 │ https://nx.dev                                                            │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ @nx/workspace (dev)                 │ 21.5.2  │ 21.6.3 │ https://nx.dev                                                            │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ @swc-node/register (dev)            │ 1.9.2   │ 1.11.1 │ https://github.com/swc-project/swc-node                                   │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ angular-eslint (dev)                │ 20.2.0  │ 20.3.0 │ https://github.com/angular-eslint/angular-eslint#readme                   │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ jiti (dev)                          │ 2.5.1   │ 2.6.1  │ https://github.com/unjs/jiti#readme                                       │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ nx (dev)                            │ 21.5.2  │ 21.6.3 │ https://nx.dev                                                            │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ wrangler (dev)                      │ 4.41.0  │ 4.42.0 │ https://github.com/cloudflare/workers-sdk#readme                          │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ @types/node (dev)                   │ 22.18.8 │ 24.6.2 │ https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ jsdom (dev)                         │ 26.1.0  │ 27.0.0 │ https://github.com/jsdom/jsdom#readme                                     │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ prettier (dev)                      │ 2.8.8   │ 3.6.2  │ https://prettier.io                                                       │
├─────────────────────────────────────┼─────────┼────────┼───────────────────────────────────────────────────────────────────────────┤
│ type-fest                           │ 4.41.0  │ 5.0.1  │ https://github.com/sindresorhus/type-fest#readme                          │
└─────────────────────────────────────┴─────────┴────────┴───────────────────────────────────────────────────────────────────────────┘
```

### Which Node.js version are you using?

22.20.0

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

### PR DESCRIPTION
**Pull request by ryo-manba**
Fixes #10040

The Details column width could be 0 when all packages are deprecated or have no homepage field, causing a validation error.

Fixed:

- Set reduce initial value to 40 (was 0)
- Ensure minimum width of 1 with `Math.max()`

### CODE REVIEW

File: reviewing/plugin-commands-outdated/src/outdated.ts [hunk 1]
```diff
@@ -260,25 +260,24 @@ function renderOutdatedTable (outdatedPackages: readonly OutdatedPackage[], opts
...
-  return table(data, {
-    ...TABLE_OPTIONS,
-    columns: {
-      ...TABLE_OPTIONS.columns,
+    }, 40)
+    tableOptions.columns = {
       // Detail column:
       3: {
-        width: detailsColumnMaxWidth,
+        width: Math.max(detailsColumnMaxWidth, 1),
```
Comment (zkochan) [inline reviewing/plugin-commands-outdated/src/outdated.ts]: is detailsColumnMaxWidth at least 40 in any case?

File: .changeset/silver-pants-sip.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@pnpm/plugin-commands-outdated": patch
```
Comment (zkochan) [inline .changeset/silver-pants-sip.md:2]:
```suggestion
"@pnpm/plugin-commands-outdated": patch
pnpm: patch
```

File: reviewing/plugin-commands-outdated/src/outdated.ts (hunk 1 above)
Comment (ryo-manba) [reply reviewing/plugin-commands-outdated/src/outdated.ts]: Right, thank you. Fixed via https://github.com/pnpm/pnpm/pull/10050/commits/0175a4ff1f611800c65742c638c0b4dec0514ee5
