### PR TITLE
fix:  should always treat local file dependency as new dependency 

### LINKED ISSUE #5381: PNPM does not sync new files in local path dependencies
### Code to reproduce the issue:

For example, we have the following file structure:

```
./
├── app
│   ├── node_modules
│   │   └── awesome -> .pnpm/file+..+pkg/node_modules/pkg
│   ├── package.json
│   └── pnpm-lock.yaml
└── pkg
    ├── bin
    └── text.txt
```

We have a local dependency in `./app/package.json`, and `./app` is initialized by `pnpm run install`. 

```js
"dependencies": {
  "awesome": "file:../pkg"
}
```

Next, we create a new file in `./pkg`

```
echo "hiya" > ./pkg/text2.txt
```

Then, `text2.txt` is in `./pkg` but not in `./app/node_modules/awesome` 😥

```
.
├── app
│   ├── node_modules
│   │   └── awesome -> .pnpm/file+..+pkg/node_modules/pkg
│   ├── package.json
│   └── pnpm-lock.yaml
└── pkg
    ├── bin
    ├── text.txt
    └── text2.txt
```

### Expected behavior:

I expect to see `text2.txt` appear in `./app/node_modules/awesome` or in `app/node_modules/.pnpm/file+..+pkg/node_modules/pkg`

### Actual behavior:

There is no `text2.txt` in `./app/node_modules/awesome` or in `app/node_modules/.pnpm/file+..+pkg/node_modules/pkg`

### Additional information:

Interestingly, changes to existing files are synced between `./pkg` and `./app/node_modules/awesome`. For example:

```shell
# Before editing
$ md5 ./pkg/text.txt
MD5 (./pkg/text.txt) = 919d117956d3135c4c683ff021352f5c
$ md5 ./app/node_modules/awesome/text.txt
MD5 (./app/node_modules/awesome/text.txt) = 919d117956d3135c4c683ff021352f5c

$ echo "oh boy" >> ./pkg/text.txt

# After editing
$ md5 ./pkg/text.txt
MD5 (./pkg/text.txt) = 6636c55e0cda2b473c75da3ff00edd52
$ md5 ./app/node_modules/awesome/text.txt
MD5 (./app/node_modules/awesome/text.txt) = 6636c55e0cda2b473c75da3ff00edd52
```

 - `node -v` prints: v16.17.0
 - Windows, macOS, or Linux?: macOS

### PR DESCRIPTION
**Pull request by await-ovo**
fix #5381, #6502 

Let's say we have a project like the following:

```
// pkg-foo/package.json
{
  "name": "pkg-foo",
  "dependencies": {
    "local-file": "file:../local-file"
  }
}

// local-file/package.json
{
  "name": "local-file",
  "version": "1.0.0",
  "dependencies": {
   "is-positive": "2.0.0" 
  }
}
```

The comparison between this PR and the current pnpm install or update is as follows:

* Before

|  | add new file  to  local-file directory | change is-positive to 3.0.0 |
| --- | --- | --- |
| pnpm update | Not synced | synced |
| pnpm update —latest | Not synced | Synced |
| pnpm update local-file | Not synced | synced |
| pnpm install | Not synced | Not synced |

* After this PR

|  | add new file  to  local-file directory | change is-positive to 3.0.0 |
| --- | --- | --- |
| pnpm update | Synced | Synced |
| pnpm update —latest | Synced | Synced |
| pnpm update local-file | Synced |Synced |
| pnpm install | Synced | Synced |

```
$ pnpm -v
8.6.1
```

### CODE REVIEW

**Comment by await-ovo** [comment]
> Can't we only do resolution if the specs in the linked in package.json change?

Does this mean that only do resolution when local file dependency's package.json changed? That would be much better, let me see how to do it.

**Comment by await-ovo** [comment]
Currently, it only do full resolution if the dependency information in package.json of the local dependency has changed ~

File: pkg-manager/core/src/install/allProjectsAreUpToDate.ts [hunk 1]
```diff
@@ -120,6 +133,31 @@ async function linkedPackagesAreUpToDate (
...
+async function isLocalFileDepUpdated (lockfileDir: string, pkgSnapshot: PackageSnapshot | undefined) {
+  if (!pkgSnapshot) return false
+  const localDepDir = path.join(lockfileDir, (pkgSnapshot.resolution as DirectoryResolution).directory)
+  const manifest = await safeReadPackageJsonFromDir(localDepDir)
+  if (!manifest) return false
+  for (const depField of DEPENDENCIES_OR_PEER_FIELDS) {
+    if (depField === 'devDependencies') continue
+    const manifestDeps = manifest[depField] ?? {}
+    const lockfileDeps = pkgSnapshot[depField] ?? {}
+    for (const depName of Object.keys(manifestDeps)) {
```
Comment (zkochan) [inline pkg-manager/core/src/install/allProjectsAreUpToDate.ts:151]: what if there are more dependencies in the lockfile than there are dependencies in the `package.json`?

Comment (await-ovo) [reply pkg-manager/core/src/install/allProjectsAreUpToDate.ts:151]: In this case, some dependencies are removed from the `package.json` file, which I still treat as up-to-date here, so it will not do resolution and changes are not synced to `node_modules/.pnpm`, with the disadvantage that the removed dependencies are still accessible in the `local-file`, I'm not quite sure if there's any other impact.

Comment (zkochan) [reply pkg-manager/core/src/install/allProjectsAreUpToDate.ts:151]: I am not sure about this behaviour. It could be unexpected

Comment (zkochan) [reply pkg-manager/core/src/install/allProjectsAreUpToDate.ts:151]: If you want to leave it as it is, then add a comment about it in the code. So that we'll remember that that is expected behaviour.

Comment (await-ovo) [reply pkg-manager/core/src/install/allProjectsAreUpToDate.ts:151]: I will update it to do resolution in this case and add some tests later~

Comment (await-ovo) [reply pkg-manager/core/src/install/allProjectsAreUpToDate.ts:151]: Well, even if we do full resolution in this case , reinstalling the dependencies will not remove the dependency(is-psitive) in `node_modules/.pnpm`, maybe it's a problem elsewhere, let's keep this behavior for now.

Comment (zkochan) [reply pkg-manager/core/src/install/allProjectsAreUpToDate.ts:151]: But it will remove the symlink. The package is not removed from `.pnpm` because we have a cache of packages there. It is controlled by this setting: https://pnpm.io/npmrc#modules-cache-max-age

Comment (await-ovo) [reply pkg-manager/core/src/install/allProjectsAreUpToDate.ts:151]: Thanks for the explanation, I updated it here.

File: pkg-manager/core/test/install/local.ts [hunk 2]
```diff
@@ -371,3 +371,50 @@ test('resolution should not fail when a peer is resolved from a local package an
...
+    },
+    lockfileVersion: LOCKFILE_VERSION,
+  })
+
+  await fs.writeFile('../local-pkg/add.js', 'added', 'utf8')
+
+  await install(manifest, await testDefaults())
+
+  await expect(fs.access('./node_modules/local-pkg/add.js')).resolves.toBeUndefined()
+})
```
Comment (zkochan) [inline pkg-manager/core/test/install/local.ts:474]: maybe let's also test that when a dependency is added to local-pkg, the lockfile gets updated.

Comment (await-ovo) [reply pkg-manager/core/test/install/local.ts:474]: done

**Review by zkochan — APPROVED** [review]
