### PR TITLE
fix: prevent circular symlinks in projects registry

### LINKED ISSUE #10411: pnpm deploy creates circular symlinks via project registry in v10.27.0, causing ELOOP errors
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

_No response_

### Which area(s) of pnpm are affected? (leave empty if unsure)

Store

### Link to the code that reproduces this issue or a replay of the bug

_No response_

### Reproduction steps

```
# In a pnpm workspace monorepo
pnpm --filter=my-package --prod deploy ./deploy-output --node-linker=hoisted

# This creates:
# ./deploy-output/.pnpm-store/v10/projects/<hash> → symlink pointing back to project
# Which causes the circular reference when traversing
```

### Describe the Bug

After upgrading from 10.26.2 to 10.27.0, `pnpm deploy` creates a `.pnpm-store/v10/projects/` directory inside the deployment target that contains circular symlinks, causing `ELOOP: too many symbolic links encountered` errors when tools try to traverse the directory.

### Expected Behavior

pnpm deploy should not create project registry symlinks inside the deployment target directory, as this creates circular references.

### Which Node.js version are you using?

22.11

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

### PR DESCRIPTION
**Pull request by zkochan**
close #10411

Might be also related to:
- #10419
- https://github.com/pnpm/pnpm/issues/10421

### CODE REVIEW

File: store/package-store/src/storeController/projectRegistry.ts [hunk 1]
```diff
@@ -17,6 +18,10 @@ export function getProjectsRegistryDir (storeDir: string): string {
  * Creates a symlink in {storeDir}/projects/{hash} → {projectDir}
  */
 export async function registerProject (storeDir: string, projectDir: string): Promise<void> {
+  // Avoid creating circular symlinks when the store is inside the project directory
+  if (isSubdir(projectDir, storeDir)) {
+    return
```
Comment (gluxon) [inline store/package-store/src/storeController/projectRegistry.ts:23]: This is a misconfiguration, right? Should we validate or throw if this happens in a future PR?

Comment (zkochan) [reply store/package-store/src/storeController/projectRegistry.ts:23]: I think it can happen in some environments, where you don't have access to the filesystem outside your project.

Comment (gluxon) [reply store/package-store/src/storeController/projectRegistry.ts:23]: Yeah, I've seen it as well. In container environments where only the project directory is writable is a common case for this.
