### PR TITLE
fix:  clean up child processes when process exited

### LINKED ISSUE #6162: esbuild process won't stop when using pnpm running multiple scripts
### Code to reproduce the issue:

Here is a minimal reproduction project on [Stackblitz](https://stackblitz.com/edit/vitejs-vite-fvof3p?file=package.json).

This is the `scripts` fields defined in `package.json`:
```json
{
  "scripts": {
    "dev": "pnpm run \"/^dev:.*/\"",
    "dev:sw": "esbuild src/sw.ts --target=es2022 --format=iife --platform=browser --outfile=public/sw.js --watch",
    "dev:web": "vite",
  },
}
```

Here I'm using `pnpm run "/<regex>/"` to run multiple scripts. The `dev:sw` script is using esbuild watch mode to build a single typescript file and the `dev:web` script is using vite to build the whole web project.

When hitting `Ctrl-C` to stop the `dev` script task, the cli output indicates that the two scripts has exited, but the esbuild process is still running.

```sh
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

### Expected behavior:

All script tasks should exit.

### Actual behavior:

The esbuild process still running in the background.

```sh
λ  app git:(main) ✗ pnpm dev

> app@0.0.0 dev
> pnpm run "/^dev:.*/"


> app@0.0.0 dev:sw
> esbuild src/sw.ts --target=es2022 --format=iife --platform=browser --outfile=public/sw.js --watch

> app@0.0.0 dev:web
> vite

[watch] build finished, watching for changes...
Port 5173 is in use, trying another one...

  VITE v4.1.4  ready in 235 ms

  ➜  Local:   http://localhost:5174/
  ➜  Network: use --host to expose
  ➜  press h to show help
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
λ  app git:(main) ✗ [watch] build started (change: "src/sw.ts")
[watch] build finished
λ  app git:(main) ✗ killall esbuild
```

I've tested it on both Windows 10 and Ubuntu and got the same issue. But it does work fine in stackblitz environment.

### Additional information:

 - `node -v` prints: `v18.13.0`
 - Windows, macOS, or Linux?: tested on both Windows and Linux

### PR DESCRIPTION
**Pull request by await-ovo**
close #6162 

When run multiple scripts at the same time, if one of them throw an error, the pnpm process exited, but the other script child processes may still be running.

Steps to reproduce:

1. `git clone git@github.com:await-ovo/pnpm-run-multiple-scripts-processes-exit-issues.git`
2. `cd pnpm-run-multiple-scripts-processes-exit-issues`
3. `pnpm run "/^dev:.*/"`

You can see that the node and web servers start on port `9999` and `9990` separately, and after waiting for 1 second, the node server throws an exception, then pnpm run process is exited.

But if you run `lsof -i:9990`, you can see that web server process doesn't exited:

```
$ lsof -i:9990    
COMMAND   PID         USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
node    98962 username  22u  IPv6 0x9fd9ab4f570298fd      0t0  TCP *:osm-appsrvr (LISTEN)
```

### CODE REVIEW

File: pnpm/src/errorHandler.ts [hunk 1]
```diff
@@ -1,7 +1,30 @@
...
 import { logger } from '@pnpm/logger'
+import pidTree from 'pidtree'
 import { REPORTER_INITIALIZED } from './main'
 
-export function errorHandler (error: Error & { code?: string }) {
+const getDescendentProcesses = promisify((pid: number, callback: (error: Error | undefined, result: number[]) => void) => {
+  pidTree(pid, { root: false }, callback)
+})
+
+const killProcesses = async () => {
```
Comment (zkochan) [inline pnpm/src/errorHandler.ts]: is this doing the same as [tree-kill](https://www.npmjs.com/package/tree-kill)? We already have tree-kill in the dependencies.

Comment (await-ovo) [reply pnpm/src/errorHandler.ts]: Yes, at first I used tree-kill directly, but it seems to have changed the original  process status to `null`,  Many of our test cases rely on a status of 1 after the process exits, so I added this dependency specifically to clean up the child processes

Comment (zkochan) [reply pnpm/src/errorHandler.ts]: I have tried to replace it with tree-kill and your test is still passing.

Comment (await-ovo) [reply pnpm/src/errorHandler.ts]: Did you test it on windows, the[ CI of this commit ](https://github.com/pnpm/pnpm/pull/6190/checks?check_run_id=11816473188)is reporting errors on linux, I get similar errors on my local macOS.

Comment (zkochan) [reply pnpm/src/errorHandler.ts]: Looks like it passes on Linux and Windows: https://github.com/pnpm/pnpm/actions/runs/4388916128/jobs/7685941878

and locally on my mac

Comment (zkochan) [reply pnpm/src/errorHandler.ts]: Actually on Linux it did not fail but Jest timed out with this error in CI: This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.

So this might be that.

**Review by zkochan — APPROVED** [review]

**Comment by mscrivo** [comment]
It seems this change caused a change in behaviour when running with `--no-bail --aggregate-output`, for example, when running:

`pnpm -r --no-bail --aggregate-output code-check:tsc`

It used to wait for it to complete and then show all errors at the bottom, now it does this:

```
> pnpm -r --no-bail --aggregate-output code-check:tsc

Scope: 39 of 40 workspace projects
browser-ext code-check:tsc$ tsc -p ./tsconfig.json --pretty
└─ Done in 4.3s
workspaces/packages/icons code-check:tsc$ tsc -p ./tsconfig.json --pretty
└─ Done in 2.4s
workspaces/packages/backend-constants code-check:tsc$ tsc -p ./tsconfig.json --pretty
└─ Done in 2.4s
workspaces/clients/load-tests code-check:tsc$ tsc -p ./tsconfig.json --pretty
└─ Done in 2.6s
workspaces/packages/react-create-context code-check:tsc$ tsc -p ./tsconfig.json --pretty
└─ Done in 1.8s
workspaces/packages/react-testing code-check:tsc$ tsc -p ./tsconfig.json --pretty
└─ Done in 1.8s
workspaces/packages/string-utils code-check:tsc$ tsc -p ./tsconfig.json --pretty
└─ Done in 1.8s
workspaces/packages/validate-code code-check:tsc$ tsc -p ./tsconfig.json --pretty
└─ Done in 1.7s
workspaces/packages/api-data code-check:tsc$ tsc -p ./tsconfig.json --pretty
└─ Done in 1.9s
workspaces/packages/feature-flags code-check:tsc$ tsc -p ./tsconfig.json --pretty
 ELIFECYCLE  Command failed with exit code 1.'length')
```

and the errors are hidden

**Comment by await-ovo** [comment]
> `pnpm -r --no-bail --aggregate-output code-check:tsc`

Hi @mscrivo, thanks for your report, I'll check it later~

**Comment by await-ovo** [comment]
> > `pnpm -r --no-bail --aggregate-output code-check:tsc`
> 
> Hi @mscrivo, thanks for your report, I'll check it later~

I don't think it's caused by this pr, but it's also caused by my [previous changes](https://github.com/pnpm/pnpm/pull/6098), I'm sorry, I'll fix it now ~

**Comment by mscrivo** [comment]
> > > `pnpm -r --no-bail --aggregate-output code-check:tsc`
> > 
> > 
> > Hi @mscrivo, thanks for your report, I'll check it later~
> 
> I don't think it's caused by this pr, but it's also caused by my [previous changes](https://github.com/pnpm/pnpm/pull/6098), I'm sorry, I'll fix it now ~

no problem at all, thanks for looking into it so quickly!
