### PR TITLE
fix(resolve-dependencies): prefer versions found in parent packages only

### LINKED ISSUE #6737: Fix preferred versions in resolve dependencies
about the possibility of overrides in `preferredVersions`, just noticed in code below(for both - before and after the pr), not sure if that can cause issues:

```js
    if (!newPreferredVersions[resolvedPackage.name]) {
      newPreferredVersions[resolvedPackage.name] = {}
    }
    if (!newPreferredVersions[resolvedPackage.name][resolvedPackage.version]) {
      newPreferredVersions[resolvedPackage.name][resolvedPackage.version] = 'version'
      // ^^ -- here the content of `preferredVersions[resolvedPackage.name][resolvedPackage.version]` is possibly modified
      // that will happen if `resolvedPackage.name` was already in `preferredVersions` ()
    }
```

_Originally posted by @zxbodya in https://github.com/pnpm/pnpm/pull/6735#discussion_r1247252526_

### PR DESCRIPTION
**Pull request by zkochan**
close #6737

### CODE REVIEW

**Review by zxbodya — APPROVED** [review]

File: pkg-manager/resolve-dependencies/src/resolveDependencies.ts [hunk 1]
```diff
@@ -537,6 +537,9 @@ export async function resolveDependencies (
       newPreferredVersions[resolvedPackage.name] = {}
     }
     if (!newPreferredVersions[resolvedPackage.name][resolvedPackage.version]) {
+      if (newPreferredVersions[resolvedPackage.name] === preferredVersions[resolvedPackage.name]) {
+        newPreferredVersions[resolvedPackage.name] = { ...preferredVersions[resolvedPackage.name] }
+      }
```
Comment (zxbodya) [inline pkg-manager/resolve-dependencies/src/resolveDependencies.ts]: alternative version:
```js
    if (!Object.prototype.hasOwnProperty.call(newPreferredVersions, resolvedPackage.name)) {
      newPreferredVersions[resolvedPackage.name] = Object.create(preferredVersions[resolvedPackage.name])
    }
```

let me check if there is a difference in performance for this

File: pkg-manager/resolve-dependencies/src/resolveDependencies.ts [hunk 2]
```diff
@@ -537,6 +537,9 @@ export async function resolveDependencies (
       newPreferredVersions[resolvedPackage.name] = {}
     }
```
Comment (zxbodya) [inline pkg-manager/resolve-dependencies/src/resolveDependencies.ts:538]: instead of the change below, this can be replaced with 

```js
    if (!Object.prototype.hasOwnProperty.call(newPreferredVersions, resolvedPackage.name)) {
      newPreferredVersions[resolvedPackage.name] = preferredVersions[resolvedPackage.name]
        ? Object.create(preferredVersions[resolvedPackage.name])
        : {}
    }
```

which is noticeably faster - 2m 50s vs 3m 16.8s for me

Comment (zkochan) [reply pkg-manager/resolve-dependencies/src/resolveDependencies.ts:538]: But in npm-resolver we are then running `Object.entries` and `Object.keys` on `newPreferredVersions[resolvedPackage.name]`, which will not list the properties if they were added with `Object.create`

Comment (zxbodya) [reply pkg-manager/resolve-dependencies/src/resolveDependencies.ts:538]: indeed that can be a problem, let's stick to safer option creating a copy
