### PR TITLE
fix(get-context): avoid excess purge prompts

### LINKED ISSUE #7320: `pnpm install` acts undesirably when multiple workspaces have already installed
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

8.6.2

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

_No response_

### Reproduction steps

To trigger this behaviour:

1. Have multiple workspaces setup.
2. `pnpm install` until completion.
3. Run `pnpm install` again.

### Describe the Bug

Multiple prompts are condensed into one line, making it terribly hard to read and the resulting prompt will act on all thus not allowing individual action.

```
Scope: all 40 workspace projects
? The modules directory at "[REDACTED]/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) ‣ ? The modules directory at "[REDACTED]/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) ‣ ? The modules directory at "[REDACTED]/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) ‣ ? The modules directory at "[REDACTED]/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) ...
```

### Expected Behavior

IMO,

- Individually prompt for each workspace and include a `[y/n/a] (a = all)` prompt action
- Provide a flag such as `-y` to accept all without interaction, useful for automation.

### Which Node.js version are you using?

16.20.2

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu 23.04

### PR DESCRIPTION
**Pull request by stevenpetryk**
pnpm sometimes needs to purge modules folders (node_modules) when certain configuration changes (in other words, when it needs to start from scratch).

This prompt, problematically, was getting triggered asynchronously for each importer in the workspace that needed a purge, which would sometimes lead to gargantuan prompts instead of one consolidated prompt.

The fix is to queue up which importers need a purge, then fire the prompter all at once.

Closes #7320

### CODE REVIEW

File: pkg-manager/get-context/src/index.ts [hunk 1]
```diff
@@ -279,28 +284,29 @@ async function validateModules (
...
       rootDir: opts.lockfileDir,
     })
   }
-  return { purged }
+
+  if (importersToPurge.length > 0) {
+    await purgeModulesDirsOfImporters(opts, importersToPurge)
+  }
+
+  return { purged: importersToPurge.length > 0 }
```
Comment (zkochan) [inline pkg-manager/get-context/src/index.ts]:
```suggestion
  const purged = importersToPurge.length > 0
  if (purged) {
    await purgeModulesDirsOfImporters(opts, importersToPurge)
  }

  return { purged }
```

File: .changeset/lemon-windows-tickle.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@pnpm/get-context": patch
+---
```
Comment (zkochan) [inline .changeset/lemon-windows-tickle.md]:
```suggestion
---
"@pnpm/get-context": patch
"pnpm": patch
---
```

**Review by zkochan — APPROVED** [review]

**Comment by stevenpetryk** [comment]
@zkochan thanks for the approval! not sure if you meant for me to merge with the approval, but just wanted to clarify that I cannot (in case you are waiting on me).
