### PR TITLE
fix: display `npm:` protocol for aliased packages in list and why

### LINKED ISSUE #8660: `pnpm why` does not list packages which are aliased via `npm:` protocol
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.12.2

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/eps1lon/pnpm-why-npm-alias

### Reproduction steps

```json
{
  "name": "pnpm-why-npm-alias",
  "dependencies": {
    "@types/react": "npm:types-react@19.0.0-rc.1"
  },
  "packageManager": "pnpm@9.12.2"
}
```

```bash
$ pnpm why @types/react
```

### Describe the Bug

Output of `pnpm why @types/react` is empty

### Expected Behavior

```bash
$ pnpm why @types/react
Legend: production dependency, optional only, dev only

dependencies:
@types/react npm:types-react@19.0.0-rc.1
```

### Which Node.js version are you using?

20.14.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

### PR DESCRIPTION
**Pull request by ryo-manba**
Fixes #8660

`pnpm list` and `pnpm why` now display `npm:` protocol aliases correctly, showing both the alias name and the actual package with `npm:` prefix.

### CODE REVIEW

File: packages/types/src/options.ts [hunk 1]
```diff
@@ -19,6 +19,7 @@ export interface FinderContext {
   name: string
   version: string
   readManifest: () => DependencyManifest
+  alias?: string
```
Comment (zkochan) [inline packages/types/src/options.ts]: I am not sure it will ever be undefined. It'll just equal the name in most cases.

Comment (ryo-manba) [reply packages/types/src/options.ts]: Indeed, I've updated.
[refactor: make alias required instead of optional](https://github.com/pnpm/pnpm/pull/10084/commits/af59daa7607c49c58cc2504830205b932fa31e37)

**Review by zkochan — APPROVED** [review]
