### PR TITLE
fix: match read/write priority when both pnpm-workspace.yaml and .npmrc exist

### LINKED ISSUE #10072: Config write/read priority mismatch when both `.npmrc` and `pnpm-workspace.yaml` exist
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

_No response_

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

_No response_

### Reproduction steps

```bash
# 1. Create a test directory
mkdir test-config-priority
cd test-config-priority

# 2. Create package.json
cat > package.json << 'EOF'
{
  "name": "test-config-priority",
  "version": "1.0.0"
}
EOF

# 3. Create both config files with different values
cat > .npmrc << 'EOF'
registry=https://registry.npmjs.org/
EOF

cat > pnpm-workspace.yaml << 'EOF'
fetchRetries: 10
EOF

# 4. Set a config value using pnpm config set
pnpm config set fetch-retries 20 --location=project

# 5. Check which file was modified
cat .npmrc
# Output:
# registry=https://registry.npmjs.org/
# fetch-retries=20

cat pnpm-workspace.yaml
# Output:
# fetchRetries: 10

# 6. Try to read the value we just set
pnpm config get fetch-retries
# Output: 10  (NOT 20!)
```

### Describe the Bug

In pnpm v10, when both `.npmrc` and `pnpm-workspace.yaml` exist in a project, `pnpm config set --location=project` writes to `.npmrc`, but `pnpm config get` reads from `pnpm-workspace.yaml`. 
This causes configuration changes to not take effect.

### Expected Behavior

When `pnpm config set fetch-retries 20 --location=project` is executed, the subsequent `pnpm config get fetch-retries` should return `20`.

### Which Node.js version are you using?

22.17.1

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

### PR DESCRIPTION
**Pull request by ryo-manba**
Fixes #10072

When both `pnpm-workspace.yaml` and `.npmrc` exist, `pnpm config set --location=project` now writes to `pnpm-workspace.yaml` (matching read priority), ensuring written values are immediately readable.

### CODE REVIEW

File: config/plugin-commands-config/src/getConfigFilePath.ts [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+interface ConfigFilePathInfo {
+  configPath: string
+  isWorkspaceYaml: boolean
+}
+
+/**
+ * Priority: pnpm-workspace.yaml > .npmrc > default to pnpm-workspace.yaml
+ */
+export function getConfigFilePath (opts: Pick<ConfigCommandOptions, 'global' | 'configDir' | 'dir'>): ConfigFilePathInfo {
```
Comment (ryo-manba) [inline config/plugin-commands-config/src/getConfigFilePath.ts:13]: This helper will also be useful for implementing `pnpm config get userconfig` to get the user's config file path (see https://github.com/pnpm/pnpm/issues/9977#issuecomment-3382481975).

File: .changeset/shy-brooms-feel.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@pnpm/plugin-commands-config": patch
```
Comment (zkochan) [inline .changeset/shy-brooms-feel.md:2]:
```suggestion
"@pnpm/plugin-commands-config": patch
pnpm: patch
```
