### PR TITLE
fix: remove empty keys from config key check

### LINKED ISSUE #3104: ` WARN  Your .npmrc file contains unknown setting:` is too sensitive
This is too sensitive.  I'm getting ` WARN  Your .npmrc file contains unknown setting:` with no setting names after it.  I have comments, "user-agent", and "registry" in mine.  It's picking up empty lines, or lines with just whitespace.

_Originally posted by @JasonKleban in https://github.com/pnpm/pnpm/issues/2981#issuecomment-767965503_

### PR DESCRIPTION
**Pull request by yaodingyd**
close #3104

### CODE REVIEW

File: packages/config/src/index.ts [hunk 1]
```diff
@@ -395,7 +395,7 @@ export default async (
   const settingKeys = Object.keys({
     ...npmConfig?.sources?.workspace?.data,
     ...npmConfig?.sources?.project?.data,
-  })
+  }).map(key => key.trim()).filter(key => key)
```
Comment (zkochan) [inline packages/config/src/index.ts]: I am a bit afraid of edge cases, so might be better this more explicit check

```suggestion
  }).filter(key => key.trim() !== '')
```

**Review by zkochan — APPROVED** [review]
