### PR TITLE
fix: don't copy optional dependencies from the store

### LINKED ISSUE #7046: Certain files aren't hardlinked on Windows, and are duplicated instead.
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

_No response_

### Which area(s) of pnpm are affected? (leave empty if unsure)

_No response_

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/MatthewKing/pnpm-issue-7046-reproduction

### Reproduction steps

There are full step-by-step instructions in the following repository: https://github.com/MatthewKing/pnpm-issue-7046-reproduction
There is also a script that reproduces the issue (`reproduce.ps1`)

A quick summary, though:
1. Restore a project with a dependency on "next".
2. Check if "node_modules\.pnpm\@next+swc-win32-x64-msvc@13.4.19\node_modules\@next\swc-win32-x64-msvc\next-swc.win32-x64-msvc.node" is hardlinked
3. The file in step 2 should be hardlinked, but it isn't. Rather, it is just duplicated.

### Describe the Bug

When using pnpm on Windows 11, some files that I would expect to be hardlinked are not hardlinked. It appears that they are simply copied, leading to duplication. In particular, files such as next-swc.win32-x64-msvc.node are quite large (110mb), and are being duplicated rather than hardlinked. This means that I'm not getting the full benefit of the content addressable store.

### Expected Behavior

I would expect that these files are hardlinked, rather than duplicated.

### Which Node.js version are you using?

18.16.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

### PR DESCRIPTION
**Pull request by zkochan**
close #7046

### CODE REVIEW

File: store/create-cafs-store/src/index.ts [hunk 1]
```diff
@@ -34,7 +35,17 @@ export function createPackageImporterAsync (
   const gfm = getFlatMap.bind(null, opts.cafsDir)
   return async (to, opts) => {
     const { filesMap, isBuilt } = gfm(opts.filesResponse, opts.sideEffectsCacheKey)
-    const pkgImportMethod = (opts.requiresBuild && !isBuilt)
+    let requiresBuild = opts.requiresBuild
+    if (requiresBuild == null) {
```
Comment (tris203) [inline store/create-cafs-store/src/index.ts]:
```suggestion
    if (requiresBuild == true) {
```

I think you meant requiresBuild == true?

**Comment by tris203** [comment]
Looks good to me, although I still don't like the idea of the lockfile being "wrong" and fixing it at install time

File: store/create-cafs-store/src/index.ts (hunk 1 above)
Comment (zkochan) [reply store/create-cafs-store/src/index.ts]: If you check my other changes in the PR, I want requiresBuild to be passed in as `undefined` if the package is optional.

Comment (tris203) [reply store/create-cafs-store/src/index.ts]: I see that now, how about if it got passed in like this? I don't love the nested ternaries but this would mean that if the item doesn't have a requiresBuild in the lockfile, it doesn't pass through the check.

This means that if we find a way to make the flag more accurate in the lock file (either through my PR  or in future, it could be incrementally adopted)

```typescript
  requiresBuild: depNode.patchFile != null || (depNode.optional ? (depNode.requiresBuild === true ? undefined : false) : depNode.requiresBuild)
```

Comment (zkochan) [reply store/create-cafs-store/src/index.ts]: Yeah, I think I can do this.

File: .changeset/mean-panthers-teach.md [hunk 2]
```diff
@@ -0,0 +1,8 @@
+---
+"@pnpm/create-cafs-store": patch
+"@pnpm/headless": patch
+"@pnpm/core": patch
+"pnpm": patch
+---
+
+Optional dependencies should not be copied from the store unless they have to be built [#7046](https://github.com/pnpm/pnpm/issues/7046).
```
Comment (gluxon) [inline .changeset/mean-panthers-teach.md]: nitpick: When I first read this message, I assumed this was not copying optional dependencies from the store at all. It looks like the behavior is to hardlink _instead_ of copying. Thoughts on this wording?

> Optional dependencies that do not have to be built will be hardlinked to the store instead of copied. This reduces disk space usage for most optional dependencies.

**Review by gluxon — APPROVED** [review]
Thanks for the fix!

File: .changeset/mean-panthers-teach.md (hunk 2 above)
Comment (tris203) [reply .changeset/mean-panthers-teach.md]: Agree, this is clearer

File: pkg-manager/core/test/install/optionalDependencies.ts [hunk 3]
```diff
@@ -648,3 +648,40 @@ describe('supported architectures', () => {
     expect(fs.readdirSync('node_modules/.pnpm').length).toBe(5)
   })
 })
+
+test('optional dependency is not copied if it does not require a build', async () => {
```
Comment (tris203) [inline pkg-manager/core/test/install/optionalDependencies.ts]:
```suggestion
test('optional dependency hardlinked to the store if it does not require a build', async () => {
```

**Review by tris203 — APPROVED** [review]
Looks good to me

File: .changeset/mean-panthers-teach.md (hunk 2 above)
Comment (zkochan) [reply .changeset/mean-panthers-teach.md]: It reduces disk space for all optional deps. Those that are built are also hardlinked from the store after they are built.
