### PR TITLE
fix: too long file names when writing to store

### LINKED ISSUE #2605: pnpm install ENAMETOOLONG
### pnpm version:

5.1.2

### Code to reproduce the issue:

I am working on the intl-ts project: https://github.com/slune-org/intl-ts

The project is still virgin and I try to install dependencies:

    pnpm install

It fails with an `ENAMETOOLONG` error.

### Expected behavior:

Install with no error.

### Actual behavior:

```bash
$ pnpm install
Lockfile is up-to-date, resolution step is skipped
Packages: +596
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 ERROR  ENAMETOOLONG: name too long, open '/home/stephane/.pnpm-store/v3/files/24/886a9c26ac23dc83f92b2692ab870714d212e65d417e41b909d2d9573ba6e41043ef3288fe40639b9686976fe182f854ce5cea296289858f809fe72502e9ef-index.json.3493966179'
Resolving: total 596, reused 0, downloaded 0
```

### Additional information:

 - `node -v` prints: v14.2.0
 - Windows, OS X, or Linux?: Linux (Gentoo)

### PR DESCRIPTION
**Pull request by zkochan**
close #2605

### CODE REVIEW

File: packages/package-requester/src/packageRequester.ts [hunk 1]
```diff
@@ -492,6 +493,17 @@ function fetchToStore (
   }
 }
 
+async function writeJsonFile (filePath: string, data: Object) {
+  const targetDir = path.dirname(filePath)
+  // TODO: use the API of @pnpm/cafs to write this file
+  // There is actually no need to create the directory in 99% of cases.
+  // So by using cafs API, we'll improve performance.
```
Comment (zkochan) [inline packages/package-requester/src/packageRequester.ts:500]: I have not done it in this PR because it needs some significant refactoring. This fix needs to be shipped fast.
