### PR TITLE
fix: config set should save the settings in the right format

### LINKED ISSUE #9355: Impossible to use some configs in pnpm 10.7
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

_No response_

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

_No response_

### Reproduction steps

I had a code to config pnpm that worked on previous version 9.6 butnot with 10.7

When I try to tape this command
`pnpm config --location project set network-concurrency '64'` it works well on 9.6 but give me an error with 10.7

I can't find the changelog that point out a change in that ....

### Describe the Bug

Error and exit prompt with 
`pnpm: Expected `concurrency` to be a number from 1 and up, got `64` (string)`

### Expected Behavior

The config is set without errors

### Which Node.js version are you using?

18.20.5

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [x] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

### PR DESCRIPTION
**Pull request by zkochan**
close #9355

### CODE REVIEW

File: config/plugin-commands-config/src/configSet.ts [hunk 1]
```diff
@@ -34,10 +35,44 @@ export async function configSet (opts: ConfigCommandOptions, key: string, value:
...
+  if (typeof value !== 'string') {
+    return value
+  }
+
+  // @ts-expect-error
+  const typeList = [].concat(types[key])
+  // @ts-expect-error
+  const isNumber = typeList.includes(Number)
+
+  value = `${value}`.trim()
```
Comment (btea) [inline config/plugin-commands-config/src/configSet.ts]: As has been judged above, if value is not a string, it will not come here, so the template literals here should not be necessary.

```suggestion
  value = value.trim()
```

**Review by btea — APPROVED** [review]
