### PR TITLE
fix: handle scoped registry keys in config get

### LINKED ISSUE #9362: cannot get some config from nearest .npmrc file with `--location=project` option in `v10.7.1`
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

v10.7.1

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/manlao/pnpm-10-7-1

### Reproduction steps

run the following command with pnpm v10.7.1:

`pnpm config --location=project get @scope:registry`

### Describe the Bug

cannot get config "@scope:registry" from .npmrc file with "--location=project" option (outputs "undefined"), and it work well without "--location=project" option.

### Expected Behavior

should output config value set in .npmrc file

### Which Node.js version are you using?

v22.14.0

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

### PR DESCRIPTION
**Pull request by ryo-manba**
Fixes #9362

With `--location=project`, scoped keys like `@scope:registry` were parsed as property paths, returning `undefined`. Now treats them as direct keys.

### CODE REVIEW

File: config/plugin-commands-config/src/configGet.ts [hunk 1]
```diff
@@ -9,13 +9,23 @@ import { parseConfigPropertyPath } from './parseConfigPropertyPath.js'
 import { settingShouldFallBackToNpm } from './settingShouldFallBackToNpm.js'
 
 export function configGet (opts: ConfigCommandOptions, key: string): { output: string, exitCode: number } {
-  if (opts.global && settingShouldFallBackToNpm(key)) {
+  const isScopedKey = key.startsWith('@')
+  if (opts.global && settingShouldFallBackToNpm(key) && !isScopedKey) {
```
Comment (KSXGitHub) [inline config/plugin-commands-config/src/configGet.ts:15]: `!isScopedKey` here contradicts a subset of `settingShouldFallBackToNpm`.

For reference, here is the content of `settingShouldFallBackToNpm.ts`:

```typescript
export function settingShouldFallBackToNpm (key: string): boolean {
  return (
    ['registry', '_auth', '_authToken', 'username', '_password'].includes(key) ||
    key[0] === '@' ||
    key.startsWith('//')
  )
}
```

Anyway, can you explain why scoped key should be excluded from global fallback?

File: config/plugin-commands-config/test/configGet.test.ts [hunk 2]
```diff
@@ -179,3 +179,43 @@ describe('config get with a property path', () => {
...
+    dir: process.cwd(),
+    cliOptions: {},
+    configDir: process.cwd(),
+    global: false,
+    rawConfig: {
+      '@scope:registry': 'https://custom-registry.example.com/',
+    },
+  }, ['get', '@scope:registry'])
+
+  expect(getOutputString(getResult)).toEqual('https://custom-registry.example.com/')
```
Comment (KSXGitHub) [inline config/plugin-commands-config/test/configGet.test.ts]:
```suggestion
  expect(getOutputString(getResult)).toBe('https://custom-registry.example.com/')
```

File: config/plugin-commands-config/test/configGet.test.ts [hunk 3]
```diff
@@ -179,3 +179,43 @@ describe('config get with a property path', () => {
...
+    dir: process.cwd(),
+    cliOptions: {},
+    configDir: process.cwd(),
+    global: true,
+    rawConfig: {
+      '@scope:registry': 'https://custom-registry.example.com/',
+    },
+  }, ['get', '@scope:registry'])
+
+  expect(getOutputString(getResult)).toEqual('https://custom-registry.example.com/')
```
Comment (KSXGitHub) [inline config/plugin-commands-config/test/configGet.test.ts]:
```suggestion
  expect(getOutputString(getResult)).toBe('https://custom-registry.example.com/')
```

File: config/plugin-commands-config/test/configGet.test.ts [hunk 4]
```diff
@@ -179,3 +179,43 @@ describe('config get with a property path', () => {
...
+test('config get with scoped registry key that does not exist', async () => {
+  const getResult = await config.handler({
+    dir: process.cwd(),
+    cliOptions: {},
+    configDir: process.cwd(),
+    global: false,
+    rawConfig: {},
+  }, ['get', '@scope:registry'])
+
+  expect(getOutputString(getResult)).toEqual('undefined')
```
Comment (KSXGitHub) [inline config/plugin-commands-config/test/configGet.test.ts]:
```suggestion
  expect(getOutputString(getResult)).toBe('undefined')
```

File: config/plugin-commands-config/src/configGet.ts (hunk 1 above)
Comment (ryo-manba) [reply config/plugin-commands-config/src/configGet.ts:15]: I think scoped keys like `@scope:registry` are read directly from `rawConfig`, so they don't need npm fallback.
But we keep `settingShouldFallBackToNpm` unchanged since it's also used in `configSet`.

Comment (KSXGitHub) [reply config/plugin-commands-config/src/configGet.ts:15]: So I guess it was for performance reasons then? Can you add a comment?

Comment (ryo-manba) [reply config/plugin-commands-config/src/configGet.ts:15]: Yes, partly for performance (avoiding npm call).
 I've added a comment.
→ [chore: add a comment](https://github.com/pnpm/pnpm/pull/10082/commits/f306836d5423b5088c6ccd2c0615af5b955bcbf0)
