### PR TITLE
fix(remove): ensure that link-workspace-packages=false is respected in single project runs in a workspace

### LINKED ISSUE #7674: `pnpm remove` links workspace packages when `link-workspace-packages=false` specified
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.15.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

Lockfile

### Link to the code that reproduces this issue or a replay of the bug

_No response_

### Reproduction steps

`pnpm remove <some-package>`

### Describe the Bug

After calling remove command pnpm links workspace packages when `link-workspace-packages=false` is specified

Screenshot 2024-02-19 at 18 03 26

### Expected Behavior

pnpm do not change another packages versions

### Which Node.js version are you using?

18.16.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

### PR DESCRIPTION
**Pull request by fpapado**
Closes #7674, by ensuring that `linkWorkspacePackagesDepth` is passed to the single project version of the `remove` command.

This started out by writing a test, but then I spotted the relevant part for the single run codepath, and the title has been updated as appropriate.

---

Original description:

This PR adds tests for https://github.com/pnpm/pnpm/issues/7674, and more specifically the reproduction mentioned in https://github.com/pnpm/pnpm/issues/7674#issuecomment-2546429388 and at https://github.com/vluoto/pnpm-remove-link-workspace-packages-false.

This is my first direct contribution to pnpm, and I might have missed a lot of things, regarding the test structure or the expectations. I used `pkg-manager/plugin-commands-installation/test/miscRecursive.ts` as my guide for these tests, and read through the relevant types and commands. Please let me know if any of this can be made more idiomatic, or whether I am going down the wrong avenue of investigation.

Since one of the tests in this PR reproduces an issue, the tests currently fail, and I am wondering what action to take next. **I would be happy to contribute a fix, but I am wary of wasting both the maintainers' and mine time, or duplicating effort**. So, please let me know if you are happy with me working on this, and I will dedicate appropriate time for it. Alternatively, I could contribute this PR with a `test.failing` or equivalent. I did not find a mention of such contribution processes in CONTRIBUTING.md, so I am following my gut feeling here 😅 

Edit: I slept on it, and it's not nice if the CI fails only this test, so I used `test.failing` to clarify the intent.

Thanks for all the work you have done on pnpm over the years!

### CODE REVIEW

File: pkg-manager/plugin-commands-installation/src/remove.ts [hunk 1]
```diff
@@ -174,6 +174,7 @@ export async function handler (
   const store = await createOrConnectStoreController(opts)
   const removeOpts = Object.assign(opts, {
     ...getOptionsFromRootManifest(opts.rootProjectManifestDir, opts.rootProjectManifest ?? {}),
+    linkWorkspacePackagesDepth: opts.linkWorkspacePackages === 'deep' ? Infinity : opts.linkWorkspacePackages ? 0 : -1,
```
Comment (fpapado) [inline pkg-manager/plugin-commands-installation/src/remove.ts:177]: Update since the draft was created: after poking at it a bit, I noticed that the single project codepath does not pass on `linkWorkspacePackagesDepth`, in the same way that the recursive codepath does. Making this change fixes the test, and the rest of the suite seems happy as well.

Sorry for the changing direction, I will stop pushing updates and wait a bit 😌

**Comment by zkochan** [comment]
Thanks, LGTM

**Comment by fpapado** [comment]
> Thanks, LGTM

Thank you as well! I have now moved this out of draft and open for review. I also changed the PR title to correctly indicate that there is a fix in it 😌
