### PR TITLE
Fixes #2171

### LINKED ISSUE #2170: Allow "force update" when workspace packages are out of sync
When having a workspace with a couple of packages, let's say `a` and `b` and executing

```
pnpm update --filter "a"
```

This will add an entry like so in the `package.json` of `a`:

```json
{
  "dependencies": {
    "b": "workspace:0.1.2"
  }
}
```

However, as soon as I now change the version of `a` let's say to `0.2.1`, I'm not able to perform `pnpm update --filter "a"` anymore:

```
ERROR  No matching version found for b@0.1.2 inside the workspace
```

How can I get out of this situation without manually changing the version of `a` in `b`?

One way I could imagine is basically a `update --force`, or maybe `update --auto-fix-workspace` to make sure that local workspace deps work.

Another option, which would work for me, would be this:
```
    "b": "workspace:*"
```

Thanks!

### LINKED ISSUE #2171: `pnpm update` doesn't resolve pre releases
This is just a tracking issue for what I described in https://github.com/pnpm/pnpm/issues/2170 so that it can be referenced in a PR.

To summarize the situation again:
I have a package called `@prisma/photon`. Its version is `2.0.0-alpha.123`.

The package `@prisma/lift` depends on it. Its entry looks like this:
```
"@prisma/photon": "workspace:*"
```

When executing
```
pnpm update --filter "@prisma/photon"
```
I get the following error:

```
 ERROR  No matching version found for @prisma/photon@* inside the workspace
```

But as `*` is provided, imo that should work.

### PR DESCRIPTION
**Pull request by timsuchanek**
I saw, that the `loose` options was already provided by using `true` as the last parameter https://github.com/npm/node-semver#functions.

Additionally adding `includePrerelease: true` also adds support for prerelease versions like `2.0.0-alpha.123`.

What is obviously missing in this PR is a test.

@zkochan would be great to get your advice on how to test this with the current setup :)

### CODE REVIEW

**Comment by timsuchanek** [comment]
This actually doesn't fix 2170, but 2171.

**Comment by zkochan** [comment]
a test like this https://github.com/pnpm/pnpm/blob/0bd287c76515a9de6c8015fe0fa8cb96fbf4e500/packages/npm-resolver/test/index.ts#L1230-L1265

**Comment by zkochan** [comment]
Next time, follow our commit message guidelines please https://github.com/pnpm/pnpm/blob/master/CONTRIBUTING.md#commit-message-guidelines

**Comment by timsuchanek** [comment]
Ok, thanks, will do! And thanks for merging 🙏

**Comment by zkochan** [comment]
@timsuchanek I have sent you an invitation to the pnpm collaborators team

**Comment by timsuchanek** [comment]
Oh, thanks a lot! Accepted that invite 😊

**Comment by zkochan** [comment]
I believe using the `includePrerelease: true` caused a regression.

Now if you have a `2.0.0-beta.0` in the monorepo, and your package depends on `^1.0.0`, pnpm will link the `2.0.0-beta.0`. For me, the expected result would be to link `2.0.0-beta.0` only to packages that depend on `^2.0.0` but I am nore sure even about that.

File: packages/npm-resolver/src/index.ts [hunk 1]
```diff
@@ -265,7 +265,10 @@ function pickMatchingLocalVersionOrNull (
     case 'version':
       return versions[spec.fetchSpec] ? spec.fetchSpec : null
     case 'range':
-      return semver.maxSatisfying(localVersions, spec.fetchSpec, true)
+      return semver.maxSatisfying(localVersions, spec.fetchSpec, {
+        includePrerelease: true,
```
Comment (zkochan) [inline packages/npm-resolver/src/index.ts:269]: I will probably have to revert this option. Also, it appears that the same options should be suplied to 

https://github.com/pnpm/pnpm/blob/01c1a55aeccf0f106b98a6122af5f256a68419f3/packages/supi/src/install/index.ts#L528
