### PR TITLE
fix: add `main` to default publish branch

### LINKED ISSUE #2995: pnpm publish should get the main branch name from config
### Code to reproduce the issue:

On a repo created in the last few months, where the default branch is `main`:

```
pnpm publish
```

### Expected behavior:

I expect it to figure out that the default is `main`, not `master`.

### Actual behavior:

I get this prompt:

```
✔ You're on branch "main" but your "publish-branch" is set to "master". Do you want to continue? (y/N) · false
```

### Additional information:

First of all, the default in pnpm should be changed to `main`, since that is what the `git` and `github` default is now.

In any case, running `git config init.defaultbranch` returns the default branch name for the current repo.

 - `node -v` prints: 15.0.1
 - Windows, macOS, or Linux?: macOS

### PR DESCRIPTION
**Pull request by yaodingyd**
close #2995

### CODE REVIEW

File: packages/plugin-commands-publishing/src/publish.ts [hunk 1]
```diff
@@ -102,7 +102,7 @@ export async function handler (
         hint: GIT_CHECKS_HINT,
       })
     }
-    const branch = opts.publishBranch ?? 'master'
+    const branch = opts.publishBranch ?? (await getDefaultBranch() || 'main')
```
Comment (zkochan) [inline packages/plugin-commands-publishing/src/publish.ts]: let's make it an array and allow both main and master. In that case, it won't be a breaking change

**Review by zkochan — CHANGES_REQUESTED** [review]

File: packages/plugin-commands-publishing/src/publish.ts [hunk 2]
```diff
@@ -102,18 +102,19 @@ export async function handler (
...
     }
-    const branch = opts.publishBranch ?? (await getDefaultBranch() || 'main')
+    const configuredBranch = opts.publishBranch ?? await getDefaultBranch()
+    const branches = configuredBranch ? [configuredBranch] : ['master', 'main']
     const currentBranch = await getCurrentBranch()
-    if (currentBranch !== branch) {
+    if (branches.includes(currentBranch)) {
       const { confirm } = await prompt({
-        message: `You're on branch "${currentBranch}" but your "publish-branch" is set to "${branch}". \
+        message: `You're on branch "${currentBranch}" but your "publish-branch" is set to "${branches.join('/')}". \
```
Comment (zkochan) [inline packages/plugin-commands-publishing/src/publish.ts]: a branch name may contain `/`, so to avoid confusion, let's probably use `|` to join the branch names. And in the error as well

**Review by zkochan — CHANGES_REQUESTED** [review]

File: .changeset/green-suns-argue.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"@pnpm/plugin-commands-publishing": major
+---
+
+Change default publish branch to main or defaultBranch in git config
```
Comment (zkochan) [inline .changeset/green-suns-argue.md]: this file should be removed.

File: packages/plugin-commands-publishing/src/publish.ts [hunk 4]
```diff
@@ -102,18 +102,19 @@ export async function handler (
...
-        message: `You're on branch "${currentBranch}" but your "publish-branch" is set to "${branch}". \
+        message: `You're on branch "${currentBranch}" but your "publish-branch" is set to "${branches.join('|')}". \
 Do you want to continue?`,
         name: 'confirm',
         type: 'confirm',
       } as any) as any // eslint-disable-line @typescript-eslint/no-explicit-any
 
       if (!confirm) {
-        throw new PnpmError('GIT_NOT_CORRECT_BRANCH', `Branch is not on '${branch}'.`, {
+        throw new PnpmError('GIT_NOT_CORRECT_BRANCH', `Branch is not on '${branches.join('/')}'.`, {
```
Comment (zkochan) [inline packages/plugin-commands-publishing/src/publish.ts]:
```suggestion
        throw new PnpmError('GIT_NOT_CORRECT_BRANCH', `Branch is not on '${branches.join('|')}'.`, {
```

File: packages/plugin-commands-publishing/test/gitChecks.ts [hunk 5]
```diff
@@ -48,11 +48,40 @@ test('publish: fails git check if branch is not on master', async () => {
       dir: process.cwd(),
     }, [])
   ).rejects.toThrow(
-    new PnpmError('GIT_NOT_CORRECT_BRANCH', "Branch is not on 'master'.")
+    new PnpmError('GIT_NOT_CORRECT_BRANCH', "Branch is not on 'master/main'.")
```
Comment (zkochan) [inline packages/plugin-commands-publishing/test/gitChecks.ts]:
```suggestion
    new PnpmError('GIT_NOT_CORRECT_BRANCH', "Branch is not on 'master|main'.")
```

**Review by zkochan — APPROVED** [review]

**Comment by zkochan** [comment]
I am unsure if using `init.defaultBranch` is right. It only gets what the global configuration is for newly created repositories, right? But the active repository's main branch might be different.

**Comment by yaodingyd** [comment]
> I am unsure if using `init.defaultBranch` is right. It only gets what the global configuration is for newly created repositories, right? But the active repository's main branch might be different.

Good point. Let me rework on this

**Comment by zkochan** [comment]
all we can do is just allow "main" and "master". I don't see a good way to find the default branch name automatically.

**Comment by yaodingyd** [comment]
how about
```
funtion optimisticallyGetDefaultBranch() {
	// git remote show origin | grep "HEAD branch" | cut -d ":" -f 2
}
```

or just `main|master`. I'm fine with that too

**Comment by zkochan** [comment]
Not sure about that. Making requests to the remote repository has many drawbacks. Like from some users it will aks the password.

Also, your suggested solution will only work when the Git CLI prints info in English.

**Comment by zkochan** [comment]
This PR is being merged to master. We don't use master. We now use main as the default branch.
