### PR TITLE
fix: update `location` option desc

### LINKED ISSUE #9396: config set writes to pnpm-workspace.yaml
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

10.8.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

_No response_

### Reproduction steps

```shell
pnpm config --help
pnpm config set side-effects-cache false --location project
```

### Describe the Bug

This is a documentation and in-line help bug.

On-line help says:
> --location <project|global>  When set to "project", the .npmrc file at the nearest package.json will be used

The same for https://pnpm.io/cli/config#--location
> --location
> When set to project, the .npmrc file at the nearest package.json will be used.

### Expected Behavior

Since pnpm `10.7.0`, the command `pnpm config set` writes to `pnpm-workspace.yaml`, so this is what the documentation should reflect.

### Which Node.js version are you using?

`22.14.0 LTS`

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [x] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu `22.04.2 LTS`

### PR DESCRIPTION
**Pull request by btea**
close #9396
sync https://github.com/pnpm/pnpm.io/pull/659

### CODE REVIEW

File: config/plugin-commands-config/src/config.ts [hunk 1]
```diff
@@ -54,7 +54,7 @@ export function help (): string {
             shortAlias: '-g',
           },
           {
-            description: 'When set to "project", the .npmrc file at the nearest package.json will be used',
+            description: 'When set to "project", the .npmrc file at the nearest package.json will be used. If no `.npmrc` file is present in the directory, the setting will be written to a `pnpm-workspace.yaml` file.',
```
Comment (MikeMcC399) [inline config/plugin-commands-config/src/config.ts]:
```suggestion
            description: 'When set to "project", the .npmrc file at the nearest package.json will be used. If no .npmrc file is present in the directory, the setting will be written to a pnpm-workspace.yaml file.',
```

This is TypeScript not Markdown, so backticks are probably not correct here.

Comment (btea) [reply config/plugin-commands-config/src/config.ts]: Thanks!

**Review by zkochan — APPROVED** [review]
