### PR TITLE
fix: correctly apply cleanupUnusedCatalogs when remove pkg

### LINKED ISSUE #9993: pnpm rm <dep> in workspace package removes entire catalog when using cleanupUnusedCatalogs
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

10.17

### Which area(s) of pnpm are affected? (leave empty if unsure)

_No response_

### Link to the code that reproduces this issue or a replay of the bug

_No response_

### Reproduction steps

1. Have pnpm monorepo with catalog and a few deps
2. set `cleanupUnusedCatalogs: true`
3. `pnpm rm <dep>` some dep that is in the catalog

### Describe the Bug

entire catalog is removed despite deps continuing to be used

### Expected Behavior

Only the removed dep is gone from catalog

### Which Node.js version are you using?

24.0.2 and 23

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

(I low key want to wait a bit so I could have been bug number 10000 lollll)

### PR DESCRIPTION
**Pull request by btea**
fix #9993

### CODE REVIEW

File: pkg-manager/plugin-commands-installation/src/remove.ts [hunk 1]
```diff
@@ -217,8 +218,23 @@ export async function handler (
     removeOpts
   )
   await writeProjectManifest(mutationResult.updatedProject.manifest)
+
+  const allProjects: Project[] = [
+    mutationResult.updatedProject as Project,
+  ]
+  // @ts-expect-error
+  if (opts.workspacePackages != null) {
```
Comment (zkochan) [inline pkg-manager/plugin-commands-installation/src/remove.ts]: shouldn't `opts.allProjects` be used instead to populate the new allProjects?

Comment (btea) [reply pkg-manager/plugin-commands-installation/src/remove.ts]: After local attempts, it was found that `opts.allProjects` was `undefined`.

**Comment by btea** [comment]
> a test would be useful

I'm not sure where to add the tests. Is the remove command related to the test case?

**Comment by btea** [comment]
The new test case is used to cover the scenario where the original allProject passed in is undefined, which leads to incorrect results.

There is no test case for removing catalog entries when deleting a dependency. I am not sure how to add it yet.

**Review by zkochan — APPROVED** [review]
