### PR TITLE
fix(dlx): print help message when no arguments are provided

### LINKED ISSUE #10633: pnpm dlx crashes when run with no arguments
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

_No response_

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

`pnpm dlx`

### Reproduction steps

Run `pnpm dlx` with no arguments

I am on MacOS 26.3 Tahoe

### Describe the Bug

PNPM crashes
```
% pnpm dlx                   
 ERROR  Cannot read properties of undefined (reading 'indexOf')

pnpm: Cannot read properties of undefined (reading 'indexOf')
    at parseWantedDependency (~/Library/pnpm/global/5/.pnpm/pnpm@10.29.3/node_modules/pnpm/dist/pnpm.cjs:111364:52)
    at ~/Library/pnpm/global/5/.pnpm/pnpm@10.29.3/node_modules/pnpm/dist/pnpm.cjs:184370:94
    at Array.map (<anonymous>)
    at Object.handler [as dlx] (~/Library/pnpm/global/5/.pnpm/pnpm@10.29.3/node_modules/pnpm/dist/pnpm.cjs:184369:51)
    at ~/Library/pnpm/global/5/.pnpm/pnpm@10.29.3/node_modules/pnpm/dist/pnpm.cjs:195529:57
    at async main (~/Library/pnpm/global/5/.pnpm/pnpm@10.29.3/node_modules/pnpm/dist/pnpm.cjs:195495:34)
    at async runPnpm (~/Library/pnpm/global/5/.pnpm/pnpm@10.29.3/node_modules/pnpm/dist/pnpm.cjs:195762:5)
    at async ~/Library/pnpm/global/5/.pnpm/pnpm@10.29.3/node_modules/pnpm/dist/pnpm.cjs:195754:7
```

### Expected Behavior

PNPM should print an error message, something like "please specify the package"

### Which Node.js version are you using?

24.13.1

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

### PR DESCRIPTION
**Pull request by ishan8351**
Running `pnpm dlx` with no arguments would crash Node.js with a TypeError as it attempted to call `.indexOf()` on an undefined variable. This PR adds a guard clause and throws a descriptive DLX_NO_PKG error and exits gracefully.

Fixes #10633

### CODE REVIEW

File: exec/plugin-commands-script-runners/src/dlx.ts [hunk 1]
```diff
@@ -88,6 +88,9 @@ export async function handler (
   opts: DlxCommandOptions,
   [command, ...args]: string[]
 ): Promise<{ exitCode: number }> {
+  if (!command && (!opts.package || opts.package.length === 0)) {
+    throw new PnpmError('DLX_NO_PKG', 'Please specify the name of the package you want to execute.')
```
Comment (zkochan) [inline exec/plugin-commands-script-runners/src/dlx.ts]: I think it should print the help text for `pnpx` and exit with 1. That's what happens when someone runs `pnpm` without args too.
