### PR TITLE
fix: no permission to delete empty directories

### LINKED ISSUE #7405: EBUSY: resource busy or locked, rmdir '/**/node_modules'
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

_No response_

### Which area(s) of pnpm are affected? (leave empty if unsure)

Operating System (Windows, MacOS, Linux)

### Link to the code that reproduces this issue or a replay of the bug

_No response_

### Reproduction steps

- Install version 8.12.0.
- The server account does not have permission to delete.

### Describe the Bug

https://github.com/pnpm/pnpm/blob/e3b98329559f5d2c65c07310d681275159f0065a/pkg-manager/modules-cleaner/src/removeDirectDependency.ts#L44C7-L48

Scenes:
When building the project in the build server, due to the new operation of deleting empty directories in version 8.12.0, when the account permissions are insufficient, the entire automatic production build will fail and related errors will be reported.

```
Error: EBUSY: resource busy or locked, rmdir '/**/node_modules'
```

As for why there is this empty `node_modules`, because we have made an image cache for the project's `node_modules`, so at the beginning of the build task, we will first create an empty directory, and then determine whether the image exists. If it does not exist, execute `pnpm install`. At this time, Trigger a new version of the trap.

### Expected Behavior

Compiled successfully

### Which Node.js version are you using?

16.17.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

### PR DESCRIPTION
**Pull request by chenxch**
fix #7405

### CODE REVIEW

File: pkg-manager/modules-cleaner/src/removeDirectDependency.ts [hunk 1]
```diff
@@ -42,8 +42,11 @@ export async function removeDirectDependency (
 }
 
 export async function removeIfEmpty (dir: string) {
-  if (await dirIsEmpty(dir)) {
-    await rimraf(dir)
+  try {
+    if (await dirIsEmpty(dir)) {
+      await rimraf(dir)
```
Comment (zkochan) [inline pkg-manager/modules-cleaner/src/removeDirectDependency.ts]: only this part fails, no? So I guess put only rimraf to try/catch. And add a comment about in what scenario it might happen.

**Comment by zkochan** [comment]
Add a changeset

File: pkg-manager/modules-cleaner/src/removeDirectDependency.ts (hunk 1 above)
Comment (chenxch) [reply pkg-manager/modules-cleaner/src/removeDirectDependency.ts]: image
This causes pnpm install to fail, causing the build process to terminate with an error.

**Review by zkochan — APPROVED** [review]
