### PR TITLE
fix(filtering): Support linked-workspace- packages='false' in workspace filtering

### LINKED ISSUE #2625: Incorrect project filtering in workspace with linked-workspace-packages=false
### Code to reproduce the issue:
```
project-1:
{
   version: 1.0.0,
   dependencies: {
      "project-2": "workspace:*"
      "project-3": "1.0.0"
   }
}

project-2:
{
   version: 1.0.0
}

project-3:
{
  version: "1.0.0"
}
```

pnpm run build --filter "project-1"...
linked-workspace-packages = false

### Expected behavior:

Should only run build (or other command) in project-1 and project-2
Because linked-workspace-packages=false, so only the workspace:*
is explicit.

### Actual behavior:
It runs the build in project-1, project-2, and project-3

### Additional information:

 - `node -v` prints: v10.19.0
 - Windows, OS X, or Linux?: osx

### PR DESCRIPTION
**Pull request by defjosiah**
Pass the linkedWorkspacePackages config to the pkg-graph,
only select packages that are explicitly referred to as workspace:...
when this setting is on.

Fixes #2625

### CODE REVIEW

**Comment by defjosiah** [comment]
I also changed up the argument order in readProjects to match the "argument, opts" pattern.
Hopefully this is okay! I felt bad adding an extra positional argument that could be confusing.

File: packages/pkgs-graph/src/index.ts [hunk 1]
```diff
@@ -75,8 +78,14 @@ export default function<T> (pkgs: Array<Package & T>): {
 
         const pkgs = R.values(pkgMap).filter(pkg => pkg.manifest.name === depName)
         if (!pkgs.length) return ''
-        const versions = pkgs.filter(({ manifest }) => manifest.version)
+        let versions = pkgs.filter(({ manifest }) => manifest.version)
           .map(pkg => pkg.manifest.version) as string[]
+
+        const strictWorkspaceMatching = !opts.linkWorkspacePackages && !isWorkspaceSpec
+        if (strictWorkspaceMatching) {
+          // keep any versions that do not equal the raw spec
```
Comment (zkochan) [inline packages/pkgs-graph/src/index.ts]: This is not correct. If link-workspace-packages is false, then the packages are linked from the workspace only if they use workspace ranges. So even if the rawSpec matches the version, it should not be linked.

File: packages/pkgs-graph/src/index.ts [hunk 2]
```diff
@@ -27,7 +27,9 @@ export type PackageNode<T> = {
   dependencies: string[],
 }
 
-export default function<T> (pkgs: Array<Package & T>): {
+export default function<T> (pkgs: Array<Package & T>, opts: {
+  linkWorkspacePackages: boolean | 'deep'
```
Comment (zkochan) [inline packages/pkgs-graph/src/index.ts]: it is enough to make make it boolean.

if opts is not optional, then this is a breaking change for pkgs-graph

File: packages/plugin-commands-listing/test/recursive.ts [hunk 3]
```diff
@@ -205,14 +205,67 @@ test('recursive list --filter', async (t) => {
...
+      },
+    },
+    {
+      name: 'project-2',
+      version: '1.0.0',
+    },
+    {
+      name: 'is-positive',
+      version: '1.0.0',
+
```
Comment (zkochan) [inline packages/plugin-commands-listing/test/recursive.ts:231]: seems like a redundant blank line

File: packages/pkgs-graph/src/index.ts (hunk 1 above)
Comment (defjosiah) [reply packages/pkgs-graph/src/index.ts]: Got it, I'll rework this!
It's a bit of a confusing case, because we have to handle workspace:* ranges, workspace:^x.x.x ranges, and just "x.x.x" ranges here.

Comment (defjosiah) [reply packages/pkgs-graph/src/index.ts]: @zkochan 
Okay, I think I have it now:
If it's strict (link-workspace-packages=false), then just immediately add to the unmatched list and exit.

**Comment by defjosiah** [comment]
I also removed my changing the api of readProjects, so it isn't a breaking change.

One question for changeset, do you want everything that was changed (even if it's just tests) to be a patch change?

**Comment by zkochan** [comment]
If only tests were changed in a package, I think there's no need for a changeset for that package.
