### PR TITLE
fix: remove pnpm-specific options before calling npm publish

### LINKED ISSUE #9646: `Unknown cli config "--git-checks". This will stop working in the next major version of npm.`
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

`10.12.1`

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/pcaversaccio/xdeployer/blob/7937f1449a9f77746a16ab4ce97b0249a5234427/.github/workflows/publish-npm.yml#L54-L58

### Reproduction steps

See [here](https://github.com/pcaversaccio/xdeployer/actions/runs/15651611919/job/44097110479#step:8:1) the release CI run:

```console
Run pnpm publish --no-git-checks

> xdeployer@3.1.16 prepublishOnly /home/runner/work/xdeployer/xdeployer
> pnpm build


> xdeployer@3.1.16 build /home/runner/work/xdeployer/xdeployer
> tsc

npm warn Unknown cli config "--git-checks". This will stop working in the next major version of npm.
npm warn Unknown user config "always-auth". This will stop working in the next major version of npm.
```

### Describe the Bug

```
npm warn Unknown cli config "--git-checks". This will stop working in the next major version of npm.
npm warn Unknown user config "always-auth". This will stop working in the next major version of npm.
```

I don't understand how to get rid of those warnings in `pnpm`?

### Expected Behavior

No warnings.

### Which Node.js version are you using?

`v24.2.0`

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [x] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu

### PR DESCRIPTION
**Pull request by ryo-manba**
Fixes #9646 

Fixed warnings when running `pnpm publish` with pnpm-specific options like `--no-git-checks`.

### CODE REVIEW

File: releasing/plugin-commands-publishing/src/publish.ts [hunk 1]
```diff
@@ -112,6 +112,40 @@ export function help (): string {
...
+ * Remove pnpm-specific CLI options that npm doesn't recognize.
+ */
+export function removePnpmSpecificOptions (args: string[]): string[] {
+  const pnpmOnlyOptions = new Set([
+    '--publish-branch',
+    '--no-git-checks',
+    '--npm-path',
+    '--embed-readme',
+    '--no-embed-readme',
+  ])
```
Comment (zkochan) [inline releasing/plugin-commands-publishing/src/publish.ts]: some of these are booleans that don't have a value. As a result, something like this will break:

```
pnpm publish --no-git-checks ./tarball-name.tgz
```

Comment (ryo-manba) [reply releasing/plugin-commands-publishing/src/publish.ts]: Thanks, fixed it.
[fix: distinguish boolean and value options when filtering](https://github.com/pnpm/pnpm/pull/10077/commits/219394d1570eb6ceb2ffb17d40a5660a17332f82)

File: .changeset/fix-git-checks-warning.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@pnpm/plugin-commands-publishing": patch
```
Comment (zkochan) [inline .changeset/fix-git-checks-warning.md:2]:
```suggestion
"@pnpm/plugin-commands-publishing": patch
pnpm: patch
```
