### PR TITLE
Modify `assert-project` to manually check store path

### LINKED ISSUE #1535: `assert-project` cannot determine store path if no project is initialized in SUPI unit tests
## Overview

**Bug Fix** 

This is a bug fix for `privatePackages/assert-project`. Note this change only affects `pnpm` developers who write unit tests. It is not visible to the user via a production codepath. 

I plan on working on this fix.

[Relevant code](https://github.com/pnpm/pnpm/blob/05a3308aaf8e1e6c8934df4e226d87afa5d9348e/privatePackages/assert-project/src/index.ts#L27)

## Behavior

**Current Behavior**: In `supi` unit tests, `project.storeHas(packageName,  packageVersion)` cannot be called unless a module has been directly installed to the project location. In other words, a project with a `node_modules` folder must be created in order to programmatically check the contents of the store. 

**Expected Behavior**: Calls to `project.storeHas(...)` should succeed even if there isn't a valid project declared in the test. The pnpm store is a global store per test case, and it can exist even if there are no packages in the system.

## Motivation

Motivated by unit tests in PR #1529

For some `supi` unit tests, I want to add packages directly to the store but not to a project. This can be done via `storeAdd(...)` instead of `addDependenciesToPackage(...)`. However, doing so causes `project.storeHas(...)` to fail.

This is especially relevant when I want to add multiple versions of a single npm package to the store. `pnpm` does not allow for this in the `package.json` (each npm module can only have 1 version). Therefore, I cannot install the packages in the project, I must add them to the store manually.

## Root Cause

[The relevant code](https://github.com/pnpm/pnpm/blob/05a3308aaf8e1e6c8934df4e226d87afa5d9348e/privatePackages/assert-project/src/index.ts#L27) is explicitly looking for `.modules.yaml` in the `node_modules/` directory in order to determine the store location.

Obviously, this fails when no packages are installed the the project, as `node_modules/` and `.modules.yaml` will not exist.

## Possible Fix

Manually pass in the store location as an opt to `project.storeHas(...)`. This will allow [the relevant code](https://github.com/pnpm/pnpm/blob/05a3308aaf8e1e6c8934df4e226d87afa5d9348e/privatePackages/assert-project/src/index.ts#L27) to find the store in cases like above.

### PR DESCRIPTION
**Pull request by nareddyt**
Closes #1535 

## Overview

Fixes the issue described in #1535.

Implemented via a new utility package, `assert-store`.

## Testing Done

- Added unit tests in `assert-store`

### CODE REVIEW

File: privatePackages/assert-project/src/index.ts [hunk 1]
```diff
@@ -39,13 +39,13 @@ export default (t: Test, projectPath: string, encodedRegistryName?: string) => {
       }
       return path.join(await project.getStorePath(), pkgFolder, 'package')
     },
-    async storeHas (pkgName: string, version?: string) {
-      const pathToCheck = await project.resolve(pkgName, version)
+    async storeHas (pkgName: string, version?: string, store?: string) {
+      const pathToCheck = store || await project.resolve(pkgName, version)
```
Comment (zkochan) [inline privatePackages/assert-project/src/index.ts]: as far as I understand, with this change, the function will only check if the store exists, not if the package/version exists in the store

File: privatePackages/assert-project/test/index.ts [hunk 2]
```diff
@@ -26,3 +26,12 @@ test('assertProject() store functions', async (t) => {
 
   t.end()
 })
+
+test('direct storeHas() without project', async (t) => {
+  const project = assertProject(t, path.join(__dirname, 'fixture/project'), 'registry.npmjs.org')
+
+  const storePath = path.join(__dirname, 'fixture/store/2')
+  await project.storeHas('is-positive', '3.1.0', storePath)
```
Comment (zkochan) [inline privatePackages/assert-project/test/index.ts]: this function is completely unrelated to `project` if the store is not the project's store.

So I think it should be a different util function. Maybe just `storeHas(storePath, pkgName, pkgVersion)`

Or something like `assertStore()` (similarly to `assertProject`). And then you can use it as `await store.has()`...

File: privatePackages/assert-project/src/index.ts (hunk 1 above)
Comment (nareddyt) [reply privatePackages/assert-project/src/index.ts]: Oops, that is correct. My bad

File: privatePackages/assert-project/test/index.ts (hunk 2 above)
Comment (nareddyt) [reply privatePackages/assert-project/test/index.ts]: Ok, that makes the most sense. I was originally confused because I thought that `assert-project` was in charge of creating the store. Taking a deeper dive into the source code, I see that is not the case.

I can make a new `assert-store` privatePackage.

**Comment by nareddyt** [comment]
What do you think of this? Created a new module called `assert-store`. This can be used by SUPI tests and even `assert-project` to abstract away the store checking.

File: privatePackages/assert-store/src/index.ts [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+import { Test } from 'tape'
+
+export default (t: Test, storePath: string, encodedRegistryName?: string) => {
+  const ern = encodedRegistryName || 'localhost+4873'
+  const store = {
+    async getStorePath () {
+      return storePath
+    },
+    async getEncodedRegistryName () {
+      return ern
```
Comment (zkochan) [inline privatePackages/assert-store/src/index.ts]: I don't think getEncodedRegistryName () and getStorePath() are needed

**Comment by zkochan** [comment]
good idea. Probably it may be used in `assert-project` as well, as it implement storeHas, storeHasNot

**Comment by nareddyt** [comment]
> good idea. Probably it may be used in `assert-project` as well, as it implements storeHas, storeHasNot for specific projects

I can make a different PR for that once this module is published on npm.

File: privatePackages/assert-store/src/index.ts (hunk 3 above)
Comment (nareddyt) [reply privatePackages/assert-store/src/index.ts]: Fixed!

**Comment by zkochan** [comment]
> I can make a different PR for that once this module is published on npm.

I don't have objections to merge this but the utils libs are not published to npm anyway

see
https://github.com/pnpm/pnpm/blob/master/packages/pnpm/package.json#L86

**Comment by nareddyt** [comment]
Ah thanks, that makes a lot of sense. Ok, I can go ahead and do the rest of the tasks once it is merged.
