### PR TITLE
fix(publish): remove workspace from devDependencies

### LINKED ISSUE #2202: pnpm doesn't remove `workspace` from `devDependencies`
### Code to reproduce the issue:
I set up a minimal reproduction here:
https://github.com/timsuchanek/prisma2-1054

Package `dummy-package-a1` has a `devDependency` to `dummy-package-2`.

While the `workspace:` version namespace is correctly removed for `dependencies`, it's not removed for `devDependencies`.
Tools that don't know the `workspace` version scheme, break.
One of these tools is https://github.com/volta-cli/volta.

Because of that, users can't install [one of our packages](https://github.com/prisma/prisma2/issues/1054), which we release with pnpm.

You can see the resulting package.json of this example here:
https://cdn.jsdelivr.net/npm/dummy-package-a1@0.0.0/package.json

It sounds like a fairly "easy" thing to fix, so in addition to cleaning up the `dependencies` before actually calling npm publish, also the `devDependencies` have to be cleaned up.

### PR DESCRIPTION
**Pull request by timsuchanek**
Closes #2202

This PR makes sure, that the `workspace:` version protocol is not only cleaned up from the `dependencies` and `optionalDependencies`, but also from `devDependencies`.

### CODE REVIEW

File: packages/plugin-commands-publishing/src/publish.ts [hunk 1]
```diff
@@ -122,6 +122,7 @@ async function makePublishManifest (dir: string, originalManifest: ImporterManif
     ...originalManifest,
     dependencies: await makePublishDependencies(dir, originalManifest.dependencies),
     optionalDependencies: await makePublishDependencies(dir, originalManifest.optionalDependencies),
+    devDependencies: await makePublishDependencies(dir, originalManifest.devDependencies),
```
Comment (zkochan) [inline packages/plugin-commands-publishing/src/publish.ts:124]: not sorted alphabetically

File: packages/plugin-commands-publishing/test/publish.ts [hunk 2]
```diff
@@ -316,6 +316,9 @@ test('convert specs with workspace protocols to regular version ranges', async (
       },
       optionalDependencies: {
         'lodash.deburr': 'workspace:^4.1.0',
+      },
+      devDependencies: {
```
Comment (zkochan) [inline packages/plugin-commands-publishing/test/publish.ts:317]: not sorted alphabetically

File: packages/plugin-commands-publishing/test/publish.ts [hunk 3]
```diff
@@ -314,6 +314,9 @@ test('convert specs with workspace protocols to regular version ranges', async (
         'is-positive': '1.0.0',
         'lodash.delay': '~4.1.0',
       },
+      devDependencies: {
+        'random-package': 'workspace:^1.2.3'
```
Comment (zkochan) [inline packages/plugin-commands-publishing/test/publish.ts:318]: random-package is not in the workspace, so this will fail

**Comment by zkochan** [comment]
:ship: 4.4.0-2
