### PR TITLE
fix(default-reporter): use loglevel to filter deprecation warnings (#4343)

### LINKED ISSUE #4343: `loglevel=error` doesn't supress warnings, such as `WARN deprecated` and ` WARN  Issues with peer dependencies found`.
### pnpm version:

6.30.0

### Code to reproduce the issue:

See screenshot. Should be trivial to reproduce, but I can provide a step-by-step reproduction if needed.

### Expected behavior:

As per the documentation (https://pnpm.io/npmrc#loglevel), warnings shouldn't be shown.

### Actual behavior:

Warnings are displayed.

### Additional information:

 - `node -v` prints: `v.16.5.0`
 - Windows, macOS, or Linux?: Linux

Screenshot 2022-02-16 14 38 06

### PR DESCRIPTION
**Pull request by milahu**
fix #4343 

... at least for `WARN deprecated`

successfully tested with `node /path/to/pnpm/packages/pnpm/spnpm.js install --loglevel error --lockfile-only`

### CODE REVIEW

File: packages/default-reporter/src/reporterForClient/reportDeprecations.ts [hunk 1]
```diff
@@ -4,15 +4,22 @@ import { map } from 'rxjs/operators'
...
     isRecursive: boolean
+    logLevel?: LogLevel
   }
 ) => {
   return deprecation$.pipe(
+    // print deprecation warnings for all logLevel except error = warn info debug
+    // TODO unswitch -> return a "null pipe"
+    filter(() => opts.logLevel != 'error'),
+    // print warnings only about deprecated packages from the root
+    filter((log) => log.depth === 0),
```
Comment (zkochan) [inline packages/default-reporter/src/reporterForClient/reportDeprecations.ts]: We need to print deprecation messages from all levels.

File: packages/default-reporter/src/reporterForClient/reportDeprecations.ts [hunk 2]
```diff
@@ -1,18 +1,23 @@
...
   opts: {
     cwd: string
     isRecursive: boolean
+    logLevel?: LogLevel
   }
 ) => {
   return deprecation$.pipe(
+    // print deprecation warnings for all logLevel except error = warn info debug
+    // TODO unswitch -> return a "null pipe"
+    filter(() => opts.logLevel != 'error'),
```
Comment (zkochan) [inline packages/default-reporter/src/reporterForClient/reportDeprecations.ts]: In this case, the stream should not be even read. Just return an empty stream instead, if loglevel is set to error.

**Review by zkochan — CHANGES_REQUESTED** [review]
Add changesets and a test.

**Comment by milahu** [comment]
changesets?

test seems challenging ...
i had a look at `packages/default-reporter/test/index.ts`
but i dont see a way to do `log$.deprecation.next(...)`
integration test should be easier. ideas?

**Comment by milahu** [comment]
thanks for your fix : )

while we're at it
i suggest we hide the progress reporting on loglevel=error and loglevel=warn

**Comment by zkochan** [comment]
I'll have to look into it. Covering it with an e2e test is too expensive.

**Review by zkochan — APPROVED** [review]
