### PR TITLE
fix: don't fail if the file already exists (Windows Reflinks)

### LINKED ISSUE #7554: Linking fails on ReFS: The file exists. (os error -2147024816) during reflink
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.14.2

### Which area(s) of pnpm are affected? (leave empty if unsure)

_No response_

### Link to the code that reproduces this issue or a replay of the bug

_No response_

### Reproduction steps

1. Create a Dev Drive
2. Install dependencies for one project to populate cache
3. Install dependencies for the other project that shares the some modules with the first project

Projects in my case:
1. `https://github.com/modrinth/knossos.git`
2. `https://github.com/vintl-dev/nuxt.git`

### Describe the Bug

pnpm crashes during linking phase due to the reflink error:
```
> corepack pnpm@latest i
Scope: all 6 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +1351
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading registry.npmjs.org/@formatjs/intl-displaynames/6.6.6: 6.00 MB/6.00 MB, done
 ERR_PNPM_LINKING_FAILED  Error: The file exists. (os error -2147024816), reflink 'U:\.pnpm-store\v3\files\bc\1a67e67dc75878b982aecde9d07d2b672a42fbd33835d49b25ab34b4ac59d9887c241adaffb56aeccca958cd7545489419bab733d5d1fe359125448e90acd3' -> 'U:\vintl-dev\nuxt\node_modules\.pnpm\https-proxy-agent@7.0.2\node_modules\https-proxy-agent_tmp_21444\dist\index.js'
Progress: resolved 1351, reused 724, downloaded 12, added 430

> 
```

### Expected Behavior

pnpm installs dependencies without any issues

### Which Node.js version are you using?

18.19.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

### PR DESCRIPTION
**Pull request by nachoaldamav**
Close #7554

### CODE REVIEW

File: fs/indexed-pkg-importer/src/index.ts [hunk 1]
```diff
@@ -131,7 +131,7 @@ function createCloneFunction (): CloneFunction {
         // If the file already exists, then we just proceed.
         // This will probably only happen if the package's index file contains the same file twice.
         // For instance: { "index.js": "hash", "./index.js": "hash" }
-        if (!err.message.startsWith('File exists')) throw err
+        if (!err.message.startsWith('File exists') && !err.message.includes('-2147024816')) throw err
```
Comment (zkochan) [inline fs/indexed-pkg-importer/src/index.ts:134]: How have you found this error code?

Comment (nachoaldamav) [reply fs/indexed-pkg-importer/src/index.ts:134]: It's in the original issue, also here https://stackoverflow.com/a/42926648

**Comment by zkochan** [comment]
add a changeset, pls

**Review by zkochan — APPROVED** [review]
