### PR TITLE
fix(config): Allow turning off forced installation in %APPDATA%

### LINKED ISSUE #1264: Regression: EEXIST: file already exists, mkdir '%APPDATA%\npm'
### pnpm version:
2.9.0 (#1244)

### Code to reproduce the issue:
`pnpm i -g <anything>` (in my case `pnpm i -g pnpm`, as I attempted to upgrade it to version `2.10.4` which came out not long ago)

### Expected behavior:
Packages are installed into `C:\NodeJS\pnpm-global\1\node_packages\…`

### Actual behavior:
`pnpm` attempts to install the packages into `%APPDATA%\npm`, which fails because I don’t want them there (and have created an empty file named `npm` in `%APPDATA%` specifically to prevent this sort of behaviour back when I still used `npm`)

### Additional information:
 - `node -v` prints: v10.5.0 (irrelevant)
 - Windows, OS X, or Linux?: Windows (duh)
 - Caused by #1244

### PR DESCRIPTION
**Pull request by ExE-Boss**
Follow‑up to #1244.

Resolves #1264.

### CODE REVIEW

File: packages/config/src/index.ts [hunk 1]
```diff
@@ -111,15 +111,15 @@ export default async (
...
       acc[camelcase(configKey)] = typeof cliArgs[configKey] !== 'undefined'
         ? cliArgs[configKey]
         : npmConfig.get(configKey)
       return acc
-    }, {})
+    }, {} as PnpmConfigs)
   pnpmConfig.rawNpmConfig = Object.assign.apply(Object, npmConfig.list.reverse().concat([cliArgs]))
-  const npmGlobalPrefix = process.env.APPDATA
+  const npmGlobalPrefix: string = pnpmConfig.rawNpmConfig['pnpm-prefix'] || process.env.APPDATA
     ? path.join(process.env.APPDATA, 'npm')
```
Comment (zkochan) [inline packages/config/src/index.ts]: this code is incorrect because when you set `pnpm-prefix`,  APPDATA will be used. You should use round brackets

```ts
  const npmGlobalPrefix: string = pnpmConfig.rawNpmConfig['pnpm-prefix'] || (process.env.APPDATA
```

Comment (ExE-Boss) [reply packages/config/src/index.ts]: I realised that when I tried to run `tsc` locally.

**Comment by zkochan** [comment]
:ship: 2.14.0
