### PR TITLE
fix: dependencies should always be explicitly grouped with peers

### LINKED ISSUE #1838: Insufficient deduping
Hi, I already posted about this in Gitter, but that conversation seems to be dead and I think it might be a bug anyway. The problem is that `styled-components` is not deduped in my dependency tree, which leads to failing styling on my generated documentation site.

### pnpm version:
`3.3.4`

### Code to reproduce the issue:
1. Clone [my project](https://github.com/cdfa/react-turn-reveal)
2. Checkout `develop`
3. `rm pnpm-lock.yaml` to force resolution
4. `pnpm i` or `pnpm i --resolution-strategy fewer-dependencies`

### Expected behavior:
```
$ pnpm list styled-components
react-turn-reveal@0.1.0 /home/cdfa/Projects/react-turn-reveal
├─┬ docz-theme-default@1.2.0
│ └─┬ styled-components@4.2.0
└── styled-components@4.2.0
```
and styled work properly.

### Actual behavior:
```
$ pnpm list styled-components
react-turn-reveal@0.1.0 /home/cdfa/Projects/react-turn-reveal
├─┬ docz-theme-default@1.2.0
│ └─┬ styled-components@4.2.0_b8333fe1de066bcb7f20c3365f51e6fb
│   └─┬ babel-plugin-styled-components@1.10.0_styled-components@4.2.0
│     └── styled-components@4.2.0_b8333fe1de066bcb7f20c3365f51e6fb
└── styled-components@4.2.0
```
and getting this warning in the browser console when running the docz server with `npm run dev`
```
It looks like there are several instances of 'styled-components' initialized in this application. This may cause dynamic styles not rendering properly, errors happening during rehydration process and makes your application bigger without a good reason.

See https://s-c.sh/2BAXzed for more info.
```
and indeed styled not rendering properly.

### Additional information:

 - `node -v` prints: `v10.15.3`
 - Windows, OS X, or Linux?: Linux

### PR DESCRIPTION
**Pull request by zkochan**
close #1838

TODO:
- [x] test `pnpm add foo bar@npm:foo`
- [x] fix the skipped tests
- [x] add a new test that covers the original issue

### CODE REVIEW

File: packages/resolve-dependencies/src/resolveDependencies.ts [hunk 1]
```diff
@@ -711,7 +711,7 @@ async function resolveDependency (
     ctx.resolvedPackagesByPackageId[pkgResponse.body.id].optional = ctx.resolvedPackagesByPackageId[pkgResponse.body.id].optional && wantedDependency.optional
 
     // we need this for saving to package.json
-    if (options.currentDepth === 0) {
+    if (options.currentDepth === 0 && !ctx.resolvedPackagesByPackageId[pkgResponse.body.id].specRaw) {
```
Comment (zkochan) [inline packages/resolve-dependencies/src/resolveDependencies.ts]: This needs to be rethinked

**Comment by zkochan** [comment]
ship 3.5.0-0

**Comment by octogonz** [comment]
Thanks for continuing to improve this feature!
