### PR TITLE
fix: `shamefullyHoist` set via `updateConfig` in `.pnpmfile.cjs`

### LINKED ISSUE #10271: [Bug] Set `shamefullyHoist` by `.pnpmfile.js` not working
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

v10.24.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

_No response_

### Link to the code that reproduces this issue or a replay of the bug

_No response_

### Reproduction steps

```cjs
// .pnpmfile.cjs
module.exports = {
  hooks: {
    updateConfig(config) {
      return Object.assign(config, {
        shamefullyHoist: true,
      });
    }
  }
};
```

### Describe the Bug

`shamefullyHoist: true` not work when it config by `.pnpmfile.cjs`

### Expected Behavior

`shamefullyHoist: true` should work.

### Which Node.js version are you using?

24.0.0

### Which operating systems have you used?

- [ ] macOS
- [x] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

### PR DESCRIPTION
**Pull request by ryo-manba**
close #10271

The derived config (`shamefullyHoist` → `publicHoistPattern`) was not being applied after the hook.

### CODE REVIEW

File: cli/cli-utils/src/getConfig.ts [hunk 1]
```diff
@@ -57,6 +57,7 @@ export async function getConfig (
         const updateConfigResult = updateConfig(config)
         config = updateConfigResult instanceof Promise ? await updateConfigResult : updateConfigResult // eslint-disable-line no-await-in-loop
       }
+      applyDerivedConfig(config)
```
Comment (zkochan) [inline cli/cli-utils/src/getConfig.ts]: but this also happens in config/config. Let's then remove the derivation from config/config and only derive here.

File: config/config/src/index.ts [hunk 2]
```diff
@@ -694,3 +673,28 @@ function addSettingsFromWorkspaceManifestToConfig (pnpmConfig: Config, {
   }
   pnpmConfig.catalogs = getCatalogsFromWorkspaceManifest(workspaceManifest)
 }
+
+// Convert shamefullyHoist to publicHoistPattern
+export function applyDerivedConfig (config: Config): void {
```
Comment (zkochan) [inline config/config/src/index.ts]: just move it to cli-utils as it isn't used anywhere else.

File: cli/cli-utils/src/getConfig.ts [hunk 3]
```diff
@@ -84,3 +85,28 @@ function isPluginName (configDepName: string): boolean {
...
+          Array.isArray(config.publicHoistPattern) &&
+          config.publicHoistPattern.length === 1 &&
+          config.publicHoistPattern[0] === ''
+        )
+    ) {
+      delete config.publicHoistPattern
+    }
+    break
+  }
+}
```
[the remark this answers is not in the document]
Comment (zkochan) [reply cli/cli-utils/src/getConfig.ts:119]: yeah, that piece of code should be moved too.

[the remark this answers is not in the document]
Comment (ryo-manba) [reply cli/cli-utils/src/getConfig.ts:119]: Thanks, fixed it.
commit: [refactor: move applyDerivedConfig to cli-utils](https://github.com/pnpm/pnpm/pull/10519/commits/8bea1e18e269620b93218acd1d92f1a7a43f3b1b)

File: pnpm/test/hooks.ts [hunk 4]
```diff
@@ -272,6 +272,48 @@ module.exports = {
   expect(nodeModulesFiles).toContain('is-number')
 })
 
+test('updateConfig hook with shamefullyHoist', async () => {
```
Comment (zkochan) [inline pnpm/test/hooks.ts]: I think it is a too heavy test for such a simple scenario. Maybe just use a unit test instead in cli-utils.

Comment (ryo-manba) [reply pnpm/test/hooks.ts]: Sorry for the delay. Fixed it.
commit: [test: use unit test for hoist: false in cli-utils](https://github.com/pnpm/pnpm/pull/10519/commits/ef052472372f72f3d3bd8c70d1dc597ab70b8f93)
