### PR TITLE
fix(dlx): `ENOENT` when `symlink=false` (#8732)

### LINKED ISSUE #8732: `symlink=false` causes `ENOENT` with `dlx`
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.12.3

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

_No response_

### Reproduction steps

```console
$ pnpm -v
9.12.3

$ pnpm config get node-linker
pnp

$ pnpm config get symlink
false

$ rm -rf ~/.cache/pnpm/

$ pnpm dlx create-next-app@latest app
Packages: +1
+
Progress: resolved 1, reused 1, downloaded 0, added 1, done
 ENOENT  ENOENT: no such file or directory, open '/home/${USER}/.cache/pnpm/dlx/mwsfpgbqzlsnu7ep27nd6x3yqi/192f8d56380-274d78/node_modules/create-next-app/package.json'

$ rm -rf ~/.cache/pnpm/

$ pnpm --config.symlink=true dlx create-next-app@latest app
Packages: +1
+
Progress: resolved 1, reused 1, downloaded 0, added 1, done
✔ Would you like to use TypeScript? … No / Yes
...
```

### Describe the Bug

I have `node-linker=pnp` and `symlink=false` in my RC file.  `pnpm dlx` raises an `ENOENT` unless I set `symlink=true`.

(`node-linker` doesn't seem to matter.  Only `symlink`.)

### Expected Behavior

`pnpm dlx` should work with `symlink=false`.

### Which Node.js version are you using?

22.11.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu

### PR DESCRIPTION
**Pull request by jonathanhefner**
Prior to this commit, if `symlink` was set to `false` (such as in an RC file), `dlx` would throw `ENOENT` because it expected the `node_modules/the-package` symlink to exist:

  ```console
  $ pnpm config get symlink
  false

  $ rm -rf ~/.cache/pnpm/

  $ pnpm dlx the-package
  Packages: +1
  +
  Progress: resolved 1, reused 1, downloaded 0, added 1, done
   ENOENT  ENOENT: no such file or directory, open '/home/${USER}/.cache/pnpm/dlx/.../
                                                    node_modules/the-package/package.json'
  ```

This commit filters the `symlink` option before installing the package, allowing the symlink to be created, preventing the error.

Fixes #8732.

### CODE REVIEW

File: exec/plugin-commands-script-runners/src/dlx.ts [hunk 1]
```diff
@@ -81,7 +81,7 @@ export async function handler (
     await add.handler({
       // Ideally the config reader should ignore these settings when the dlx command is executed.
       // This is a temporary solution until "@pnpm/config" is refactored.
-      ...omit(['workspaceDir', 'rootProjectManifest'], opts),
+      ...(omit(['workspaceDir', 'rootProjectManifest', 'symlink'] as Array<keyof DlxCommandOptions>, opts) as DlxCommandOptions),
```
Comment (jonathanhefner) [inline exec/plugin-commands-script-runners/src/dlx.ts]: This is terribly hacky.  The problem is `handler` is pretending that `opts` only contains the keys of `DlxCommandOptions`, but, in actuality, other keys are also present, such as `symlink`.

I could add `'symlink'` to [`Pick<Config, ...>`](https://github.com/pnpm/pnpm/blob/7cd0d20bb27e49354187cacce3fdd4ae090127f2/exec/plugin-commands-script-runners/src/dlx.ts#L67), but that doesn't seem right.

I think a proper typechecked solution would be for `handler` to recognize that `opts` can be anything, and to use a `pick` function instead `omit`.  But that would be a larger change.

Or, if looser typechecking is fine, we could use an `omit` function that accepts any keys and returns `Partial<DlxCommandOptions>`.

Thoughts?

Comment (zkochan) [reply exec/plugin-commands-script-runners/src/dlx.ts]: > I could add 'symlink' to [Pick<Config, ...>](https://github.com/pnpm/pnpm/blob/7cd0d20bb27e49354187cacce3fdd4ae090127f2/exec/plugin-commands-script-runners/src/dlx.ts#L67), but that doesn't seem right.

you can do this

**Comment by zkochan** [comment]
The best solution would be for the dlx command to ignore the `.npmrc` file in the current working directory. Except maybe registry configurations from that file. But that's really not easy to do, so the workaround should be fine for now.

**Comment by jonathanhefner** [comment]
> The best solution would be for the dlx command to ignore the `.npmrc` file in the current working directory. Except maybe registry configurations from that file. But that's really not easy to do, so the workaround should be fine for now.

Alright, sounds good.  Done! :+1:

**Review by zkochan — APPROVED** [review]

**Comment by jonathanhefner** [comment]
Thank you for the review, @zkochan! :bow:
