### PR TITLE
fix: searching for auth token for URL with port

### LINKED ISSUE #6354: ERR_PNPM_FETCH_401
Hi,

I have an issue with `pnpm`, when I'm trying to install my private npm packages from my private npm registry (in this case AWS Codeartifact), I'm getting the error:

```
#11 32.53  ERR_PNPM_FETCH_401  GET https://<mydomain>-dom-<accountid>.d.codeartifact.us-east-1.amazonaws.com:443/npm/<myrepo>-repo/@<myorg2>/<mypackage>/-/<mypackage>-1.0.35.tgz: Unauthorized - 401
#11 32.53 
#11 32.53 No authorization header was set for the request.
#11 32.53 
#11 32.53 These authorization settings were found:
#11 32.53 @<myorg1>:registry=https://<mydomain>-dom-<accountid>.d.codeartifact.us-east-1.amazonaws.com/npm/<myrepo>-repo/
#11 32.53 @<myorg2>registry=https://<mydomain>-dom-<accountid>.d.codeartifact.us-east-1.amazonaws.com/npm/<myrepo>-repo/
```

here is my `.npmrc`:
```
registry=https://registry.npmjs.org/
@<myorg1>:registry=https://<mydomain>-dom-<accountid>.d.codeartifact.us-east-1.amazonaws.com/npm/<myrepo>-repo/
@<myorg2>:registry=https://<mydomain>-dom-<accountid>.d.codeartifact.us-east-1.amazonaws.com/npm/<myrepo>-repo/
//<mydomain>-dom-<accountid>.d.codeartifact.us-east-1.amazonaws.com/npm/<myrepo>-repo/:always-auth=true
//<mydomain>-dom-<accountid>.d.codeartifact.us-east-1.amazonaws.com/npm/<myrepo>-repo/:_authToken=<mytoken>
```

package.json:
```
...
"dependencies": {
    "@<myorg2>/<mypackage>": "1.0.35",
}
...
```

 - node:18.14.0-bullseye-slim
 - Linux
 - pnpm version: 8.1.1

### PR DESCRIPTION
**Pull request by zkochan**
close #6354

### CODE REVIEW

**Review by juanpicado — APPROVED** [review]

File: network/auth-header/src/index.ts [hunk 1]
```diff
@@ -22,12 +23,23 @@ function getMaxParts (uris: string[]) {
...
+  if (urlWithoutPort !== uri) {
+    return getAuthHeaderByURI(authHeaders, maxParts, urlWithoutPort)
+  }
   return undefined
 }
+
+function removePort (originalUrl: string) {
+  const urlObj = new URL(originalUrl)
+  if (urlObj.port === '') return originalUrl
+  const newUrlObj = new URL(`${urlObj.protocol}//${urlObj.hostname}${urlObj.pathname}${urlObj.search}${urlObj.hash}`)
```
Comment (anonrig) [inline network/auth-header/src/index.ts:43]: Is there a specific reason for not calling urlObj.port = “”? This line allocates a lot of string, and adds 200ns for just calling new URL.

Comment (zkochan) [reply network/auth-header/src/index.ts:43]: Yes, you are right. I'll release this patch ASAP https://github.com/pnpm/pnpm/pull/6717

Comment (anonrig) [reply network/auth-header/src/index.ts:43]: Thanks!
