### PR TITLE
fix: show emptry string instead of undefined when package.json has no name

### LINKED ISSUE #2005: `pnpm run` when package.json does not have "name"
I am not sure if it was intended behavior, but pnpm displays package name as literally `undefined` when `package.json` has no `"name"` field.

### `npm test`

```
> package-name@0.1.2 test /home/user/repo
> node test.js

...
```

### `pnpm test`

```
> package-name test /home/user/repo
> node test.js

...
```

### `npm test`

```
> @ test /home/user/repo
> node test.js

...
```

### `pnpm test`

```
> undefined test /home/user/repo
> node test.js

...
```

### PR DESCRIPTION
**Pull request by yaodingyd**
fix #2005

### CODE REVIEW

File: packages/lifecycle/src/runLifecycleHook.ts [hunk 1]
```diff
@@ -91,7 +91,7 @@ export default async function runLifecycleHook (
 
 function getId (manifest: ImporterManifest | DependencyManifest) {
   if (!manifest.name) {
-    return undefined
+    return ''
```
Comment (zkochan) [inline packages/lifecycle/src/runLifecycleHook.ts:96]: I think if this is not covered with a test, at least add this comment

```suggestion
    // Using an empty string instead of undefined or null
    // because this gets printed to the console
    return ''
```
